#FROM node:16 as build-stage

#WORKDIR /usr/src/app/frontend

#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN npm run build

#FROM nginx:1.19.7 as production-stage
#COPY ./dist /usr/share/nginx/html
#COPY --from=build-state /usr/src/app/frontend/dist /usr/share/nginx/html

#EXPOSE 80

#CMD ["npm", "run", "serve"]
#CMD ["nginx", "-g","daemon off;"]



# etapa de producción
FROM nginx:1.19.7 
COPY ./dist /usr/share/nginx/html

COPY entrypoint.sh /
COPY default.conf /etc/nginx/conf.d/
RUN chmod +x /entrypoint.sh
EXPOSE 80
EXPOSE 8080
ENTRYPOINT [ "/entrypoint.sh" ]
