export default {
						contentt : {
							title  : "",
							fields : [
								{
									key 		: "code",
									text 		: "code",
									type 		: "text",
									// list 		: "requirements",
									show 		: true,
									rules 		: "",
									// item_value 	: "key",
									// item_text 	: "text",
									cols 		: 12,
								},
								{
									key 		: "description",
									text 		: "description",
									type 		: "textarea",
									// list 		: "suppliers",
									show 		: false,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "stock",
									text 		: "stock",
									type 		: "`number",
									// list 		: "centers",
									show 		: false,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "value_per_product",
									text 		: "value_per_product",
									type 		: "number",
									// list 		: "laboratories",
									show 		: false,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "total_quantity_per_product",
									text 		: "total_quantity_per_product",
									type 		: "number",
									// list 		: "radiologys",
									show 		: false,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "unit_value",
									text 		: "unit_value",
									type 		: "number",
									// list 		: "pharmacys",
									show 		: true,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "vat",
									text 		: "vat",
									type 		: "number",
									// list 		: "supplies",
									show 		: true,
									rules 		: "",
									// item_value 	: "",
									// item_text 	: "",
									cols 		: 12,
								},
								{
									key 		: "laboratory",
									text 		: "laboratory",
									type 		: "text",									
									show 		: true,
									rules 		: "",
									cols 		: 12,
								},
								{
									key 		: "expiration_date",
									text 		: "expiration_date",
									type 		: "date_range",
									one_date 	: true,									
									show 		: true,
									rules 		: "",
									cols 		: 12,
								},
								{
									key 		: "lcte",
									text 		: "lcte",
									type 		: "text",									
									show 		: true,
									rules 		: "",
									cols 		: 12,
								},
								/*{
									key 		: "total",
									text 		: this.$t("total"),
									type 		: "text",									
									show 		: true,
									disabled  	: true,
									is_to_sum   : {},
									rules 		: "",
									cols 		: 12,
								},*/

							]
						},					
						listss 	: {
						/*	requirements : [
								{ text : "si", key  : "si" },
								{ text : "no", key  : "no" }
							],
							suppliers : [],
							centers   : [],
							laboratories : [],
							radiologys : [],
							pharmacys  : [],
							supplies  : [],*/

						}, 
						headd 	: { 
							title : "new_item",
						},					
						requestss :{
							edit 	: "",
							create 	: "",
							action 	: "create",
							action_key : "content",

						},
						showw : {
							actions : true,
						},
					}