export default [
    {
        key 		: "service",
        text 		: "service",
        type 		: "select",
        enable 		: true,
        icon 		: "mdi-face-agent", 
        item_value 	: "id",
        item_text 	: "name",
        global_list : "Servicios",
        list 		: [
            "Medico General",
            "Odontologia",
            "Urgencia"
        ],
        cols 		: 4,
        action 		: "set_service",
        return_obj  : true,
    },
    {
        key 		: "sub_service",
        text 		: "service",
        type 		: "select",
        enable 		: true,
        icon 		: "mdi-face-agent", 
        item_value 	: "id",
        item_text 	: "name",
        global_list : "Consulta 1er nivel",
        list 		: [
            "Medico General",
            "Odontologia",
            "Urgencia"
        ],
        cols 		: 4,
        action 		: "set_sub_service",
        return_obj  : true,
    },
    {
        key 		: "program",
        text 		: "program",
        type 		: "select",
        enable 		: true,
        icon 		: "mdi-face-agent", 
        item_value 	: "id",
        item_text 	: "name",
        global_list : "Programas",
        list 		: [
            "Medico General",
            "Odontologia",
            "Urgencia"
        ],
        cols 		: 4,
        action 		: "set_program",
        return_obj  : true,
    },
    {
        key 		: "doctor",
        text 		: "medico",
        type 		: "select",
        global_list : "doctors",
        item_value  : "User.id",
        item_text 	: "User.name",
        cols 		: 4,
        action 		: "",
    },
    {
        key 		: "assignedDate",
        type 		: "date_range",
        text 		: "assignedDate",
        cols 		: 4,
        action 		: "assigned_date",
        clearIsNull : true,
    },
    {
        key 		: "hour",
        type 		: "select",
        text 		: "hour",
        cols 		: 4,	
        get_list 	: "",
        list 		: "turns",
        action 		: "get_times",
        item_value  : "id",
        item_text 	: "hour",
        clearIsNull : true,
    },
    {
        key 			: "moderating_fee_value", // valor_cuota_modera
        // key_main 		: "serviceprovider",
        text 			: "amount",
        prepend_text 	: "$",
        type 			: "number",
        enable 			: true,
        icon 			: "mdi-currency-usd", 
        cols 			: 4,
        
    },
    {
        key 		: "status",
        text 		: "state",
        type 		: "select",
        enable 		: true,
        icon 		: "mdi-state-machine", 
        item_value 	: "id",
        item_text 	: "name",
        action 		: "set_status",
        global_list : "status",
        list 		: [
            "En espera",
            "Triage",
            "Revision Medica",
            "Revision Enfermaria",
            "Alta medica",
            "Alta erfermeria",
            "Facturacion"
        ],
        cols 		: 4,
        
    },
    {
        key 		: "space",
        type 		: "space",
        text 		: "",
        cols 		: 12,	
        get_list 	: "",
        action 		: "",
    }
]