module.exports = [
	{
		name        : 'PARTICULAR',
      	nit         : '',
      	TypeCenterId 	: 1, 	      	
		code 		: "",
		mobilityCode : "",
		regime 		: "AMBOS REGÍMENES",
      	email       : '',
		RegimeId	: 4,
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'SOAT',
      	nit         : '',
      	TypeCenterId 	: 1, 	      	
		code 		: "",
		mobilityCode : "",
		regime 		: "AMBOS REGÍMENES",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'COOSALUD EPS-S',
      	nit         : '900226715',
      	TypeCenterId 	: 1, 	      	
		code 		: "ESS024 - EPS042",
		mobilityCode : "ESSC24 - EPSS42",
		regime 		: "AMBOS REGÍMENES",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'NUEVA EPS',
      	nit         : '900156264',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS037 - EPSS41 ",
		mobilityCode : "EPSS37 - EPS041",
		regime 		: "AMBOS REGÍMENES",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},	
	{
		name        : 'MUTUAL SER',
      	nit         : '806008394',
      	TypeCenterId 	: 1, 	      	
		code 		: "ESS207 - EPS048",
		mobilityCode : "ESSC07 - EPSS48",
		regime 		: "AMBOS REGÍMENES",
      	email       : '',
      	description : '',     	
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},	 
	{
		name        : 'ALIANSALUD EPS',
      	nit         : '830113831',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS001",
		mobilityCode : "EPSS01",
		regime 		: "CONTRIBUTIVO",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	
	{
		name        : 'SALUD TOTAL EPS S.A.',
      	nit         : '800130907',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS002",
		mobilityCode : "EPSS02",
		regime 		: "CONTRIBUTIVO",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'EPS SANITAS',
      	nit         : '800251440',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS005",
		mobilityCode : "EPSS05",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'EPS SURA',
      	nit         : '800088702',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS010",
		mobilityCode : "EPSS10",
		regime 		: "CONTRIBUTIVO",
      	email       : 'demo@demo.com',
      	description : 'Description Demo',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},     
	{
		name        : 'FAMISANAR',
      	nit         : '830003564',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS017",
		mobilityCode : "EPSS17",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},	
	{
		name        : 'SERVICIO OCCIDENTAL DE SALUD EPS SOS',
      	nit         : '805001157',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS018",
		mobilityCode : "EPSS18",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'SALUD MIA ',
      	nit         : '900914254',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS046",
		mobilityCode : "EPSS46",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'COMFENALCO VALLE',
      	nit         : '890303093',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS012",
		mobilityCode : "EPSS12",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},   
	{
		name        : 'COMPENSAR EPS',
      	nit         : '860066942',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS008",
		mobilityCode : "EPSS08",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},    
	{
		name        : 'EPM - EMPRESAS PUBLICAS DE MEDELLIN',
      	nit         : '890904996',
      	TypeCenterId 	: 1, 	      	
		code 		: "EAS016",
		mobilityCode : "N/A ",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'FONDO DE PASIVO SOCIAL DE FERROCARRILES NACIONALES DE COLOMBIA',
      	nit         : '800112806',
      	TypeCenterId 	: 1, 	      	
		code 		: "EAS027",
		mobilityCode : "N/A",
		regime 		: "CONTRIBUTIVO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},   
	{
		name        : 'CAJACOPI ATLANTICO',
      	nit         : '890102044',
      	TypeCenterId 	: 1, 	      	
		code 		: "CCF055",
		mobilityCode : "CCFC55",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'CAPRESOCA',
      	nit         : '891856000',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPS025",
		mobilityCode : "EPSC25",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'COMFACHOCO',
      	nit         : '891600091',
      	TypeCenterId 	: 1, 	      	
		code 		: "CCF102",
		mobilityCode : "CCFC20",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'COMFAMILIAR DE LA GUAJIRA',
      	nit         : '892115006',
      	TypeCenterId 	: 1, 	      	
		code 		: "CCF023",
		mobilityCode : "CCFC23",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},  
	{
		name        : 'COMFAORIENTE',
      	nit         : '890500675',
      	TypeCenterId 	: 1, 	      	
		code 		: "CCF050",
		mobilityCode : "CCFC50",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'EPS FAMILIAR DE COLOMBIA (Antes ComfaSucre)',
      	nit         : '901543761',
      	TypeCenterId 	: 1, 	      	
		code 		: "CCF033",
		mobilityCode : "CCFC33",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'ASMET SALUD',
      	nit         : '900935126',
      	TypeCenterId 	: 1, 	      	
		code 		: "ESS062",
		mobilityCode : "ESSC62",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'ECOOPSOS ESS EPS-S',
      	nit         : '901093846',
      	TypeCenterId 	: 1, 	      	
		code 		: "ESS091",
		mobilityCode : "ESSC91",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'EMSSANAR E.S.S.',
      	nit         : '901021565',
      	TypeCenterId 	: 1, 	      	
		code 		: "ESS118",
		mobilityCode : "ESSC18",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'CAPITAL SALUD EPS-S',
      	nit         : '900298372',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSS34",
		mobilityCode : "EPSC34",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'SAVIA SALUD EPS',
      	nit         : '900604350',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSS40",
		mobilityCode : "EPS040",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'DUSAKAWI EPSI',
      	nit         : '824001398',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSI01",
		mobilityCode : "EPSIC1",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},  
	{
		name        : 'ASOCIACION INDIGENA DEL CAUCA EPSI',
      	nit         : '817001773',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSI03",
		mobilityCode : "EPSIC3",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'ANAS WAYUU EPSI',
      	nit         : '839000495',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSI04",
		mobilityCode : "EPSIC4",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'MALLAMAS EPSI',
      	nit         : '837000084',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSI05",
		mobilityCode : "EPSIC5",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},
	{
		name        : 'PIJAOS SALUD EPSI ',
      	nit         : '809008362',
      	TypeCenterId 	: 1, 	      	
		code 		: "EPSI06",
		mobilityCode : "EPSIC6",
		regime 		: "SUBSIDIADO",
      	email       : '',
      	description : '',
      	createdAt   : new Date(),
      	updatedAt   : new Date()
	},

]
   