// Array de barrios
module.exports = [
    "Abajo de la Loma",
    "Altos de Jesús",
    "Altos de Sevilla",
    "Bella Murillo",
    "Bonanza",
    "Buena Esperanza",
    "Cachimbero",
    "Calle Larga",
    "Centro",
    "Costa Hermosa",
    "El Manantial",
    "El Parque",
    "El Pasito",
    "El Porvenir",
    "El Río",
    "El Roble",
    "El Tucán",
    "El Triunfo",
    "El Vivero",
    "Hipódromo",
    "Juan Dominguez Romero",
    "La Bonga",
    "La Central",
    "La María",
    "La Siete de Agosto",
    "Las Margaritas",
    "Las Moras",
    "Las Trinitarias",
    "Las Villas",
    "Manuela Beltrán",
    "Mi Ranchito",
    "Nuevo Horizonte",
    "Porvenir",
    "Pradera",
    "Puerto Belén",
    "Salvador",
    "San Antonio",
    "San Vicente",
    "Santa Inés",
    "Santa Isabel",
    "Santa María",
    "Soledad 2000",
    "Villa Adela",
    "Villa Angelita",
    "Villa Estadio",
    "Villa Karla",
    "Villa Las Moras",
    "Villa Merly",
    "Villa Sol"
  ];