module.exports = [
    // { 
    //     key : "AttentionId",
    //     type : "boxex", // string
    //     text : "Numbero de Atencion", 
    //     x : 1,
    //     y : 1, 

    // },// DataTypes.INTEGER,
    // {
    //     key: "UserId",
    //     type : "text",
    //     text : "",
    // },// DataTypes.INTEGER,
    {
        key: "date",
        type : "boxes",
        text : "Fecha",
        action: "setDate",
        x : 370, 
        y : 105,
        len : 10,
        space : 9,
        size : 8,

    },// DataTypes.STRING,
    {
        key: "time",
        type : "boxes",
        text : "Hora",
        action: "setDate",
        x : 486, 
        y : 105,
        len : 10,
        space : 9.2,
        size : 8,
    },// DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "INFORMACIÓN DEL PRESTADOR",
    //     cols : 12, 
    // },
   
    {
        key: "providerName",
        type : "text",
        text : "Nombre Prestador",
        x : 130, 
        y : 133,
    },// DataTypes.STRING,
    {
        key: "providerTypeId",
        type : "select",
        text : "Tipo de identificacion Prestador",        
        itemText : "name",
        itemValue : "key",
        option : {
            nit : { key : "nit", name :"NIT", x : 415.5, y: 121.7 , w: 5, h : 5},
            cc : { key : "cc", name :"CC", x : 415.5, y: 131.7 , w: 5, h : 5},
        }

    },// DataTypes.STRING,
    {
        key: "providerNumberId",
        type : "condition",
        text : "Numero identificacion",
        keyCondition : "providerTypeId",
            len : 11,
            option : {
                nit : { key : "nit", x : 424.2 , y : 124, len: 11,  space : 9, size : 7 },
                cc  : { key : "cc", x : 424.2, y : 133,  isText : true, size: 7}
            }
    },// DataTypes.STRING,
    {
        key: "providerCode",
        type : "boxes",
        text : "Codigo",
        isInverted: true,
        x : 211,
        y : 143,
        len : 11,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "providerAddress",
        type : "text",
        text : "Direccion",
        x : 298,
        y : 142,
    },// DataTypes.STRING,
    {
        key: "providerPhoneCode",
        type : "boxes",
        text : "Codigo Telefono",
        isInverted: true,
        x : 149,
        y : 153,
        len : 4,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "providerPhoneNumber",
        type : "boxes",
        text : "Numero de Telefono",
        isInverted : true,
        x : 211,
        y : 153,
        len : 6,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "providerState",
        type : "text",
        text : "Departamento",
        x: 272,
        y: 162,
    },// DataTypes.STRING,
    {
        key: "providerCity",
        type : "text",
        text : "Municipio",
        x: 414,
        y: 162,
    },// DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "DATOS DEL PACIENTE",
    //     cols : 12, 
    // },
    {
        key: "patientFullName",
        type : "text",
        text : "Nombre Completo",
        x : 65,
        y : 180,
    },// DataTypes.STRING,
    {
        key: "patientTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option : {
            5:{ key : "5"/* "registro-civil" */ , name : "Registro Civil", x : 69, y: 207.8 , w: 5, h : 5},
            2:{ key : "2"/* "tarjeta-id" */ , name : "Tarjeta de identidad", x : 69, y: 217.8 , w: 5, h : 5},
            11:{ key : "1"/* "cedula" */ , name : "Cedula de ciudadania", x : 69, y: 227 , w: 5, h : 5},
            3:{ key : "3", name : "Cédula de extranjería", x : 69, y: 236.5 , w: 5, h : 5},
            4:{ key : "4"/* "pasaporte" */ , name : "Pasaporte", x : 166.7, y: 207.8 , w: 5, h : 5},
            7:{ key : "7"/* "adulto-sin-id" */ , name : "Adulto sin identificacion", x : 166.7, y: 217.8 , w: 5, h : 5},
            8:{ key : "8"/* "menor-sin-id" */ , name : "Menor sin identificacion", x : 166.7, y: 227 , w: 5, h : 5},
        }
    },// DataTypes.STRING,
    {
        key: "patientNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted : true,
        x : 495,
        y : 209,
        len : 15,
        space : 8.8,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "patientBirthDate",
        type : "boxes",
        text : "Fecha de Nacimiento",
        action : "setDate",
        x : 415,
        y : 237,
        len : 9,
        space : 8.8,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "patientAddress",
        type : "text",
        text : "Direccion",
        x : 165,
        y : 247
    },// DataTypes.STRING,
    {
        key: "patientPhone",
        type : "text",
        text : "Telefono",
        x : 450,
        y : 247,
    },// DataTypes.STRING,
    {
        key: "patientState",
        type : "text",
        text : "Departamento",
        x : 122,
        y : 256,
    },// DataTypes.STRING,
    {
        key: "patientCity",
        type : "text",
        text : "Municipio",
        x : 343,
        y: 256,
    },// DataTypes.STRING,
    {
        key: "patientServiceProviderName",
        type : "text",
        text : "Entidad responsable del pago",
        x : 174,
        y : 265.2,
    },// DataTypes.STRING,
    {
        key: "patientServiceProviderCode",
        type : "boxes",
        text : "Codigo de entidad",
        isInverted : true,
        x : 522,
        y : 265.2,
        len : 5,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "DATOS DE LA PERSONA RESPONSABLE DEL PACIENTE",
    //     cols : 12, 
    // },
    {
        key: "tutorFullName",
        type : "text",
        text : "Nombre del responsable",
        x : 69,
        y : 284.5,
    },// DataTypes.STRING,
    {
        key: "tutorTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option : {
            5:{ key : "5"/* "registro-civil" */ , name : "Registro Civil", x : 69, y: 312.1 , w: 5, h : 5},
            2:{ key : "2"/* "tarjeta-id" */ , name : "Tarjeta de identidad", x : 69, y: 321.8 , w: 5, h : 5},
            1:{ key : "1"/* "cedula" */ , name : "Cedula de ciudadania", x : 69, y: 331 , w: 5, h : 5},
            3:{ key : "3", name : "Cédula de extranjería", x : 69, y: 340.3 , w: 5, h : 5},
            4:{ key : "4"/* "pasaporte" */ , name : "Pasaporte", x : 166.7, y: 312.1 , w: 5, h : 5},
            3:{ key : "7"/* "adulto-sin-id" */ , name : "Adulto sin identificacion", x : 166.7, y: 321.8 , w: 5, h : 5},
            3:{ key : "8"/* "menor-sin-id" */ , name : "Menor sin identificacion", x : 166.7, y: 331 , w: 5, h : 5},
        }
    },// DataTypes.STRING,
    {
        key: "tutorNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted : true,
        x : 495,
        y : 313.1,
        len : 5,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "tutorBirthDate",
        type : "boxes",
        text : "Fecha de Nacimiento",
        action : "setDate",        
        x : 415,
        y : 341.1,
        len : 9,
        space : 9,
        size : 8,
    },
    {
        key: "tutorAddress",
        type : "text",
        text : "Direccion",
        x : 165.5,
        y: 351,
    },// DataTypes.STRING,
    {
        key: "tutorPhone",
        type : "boxes",
        text : "Telefono",
        isInverted : true,
        x : 522,
        y : 351,
        len : 8,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "tutorState",
        type : "text",
        text : "Departamento",
        x: 123,
        y: 360,
    },// DataTypes.STRING,
    {
        key: "tutorCity",
        type : "text",
        text : "Municipio",
        x :344.5,
        y : 359.5,
    },// DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "PROFESIONAL QUE SOLICITA LA REFERENCIA Y SERVICIO AL CUAL REMITE",
    //     cols : 12, 
    // },
    {
        key: "personRequestingFullName",
        type : "text",
        text : "Nombre",
        x : 104,
        y: 388.5,
        
    },// DataTypes.STRING,
    {
        key: "personRequestingPhoneCode",
        type : "boxes",
        text : "Codigo de Telefono",
        isInverted : true,
        x : 406,
        y : 389,
        len : 4,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "personRequestingPhoneNumber",
        type : "boxes",
        text : "Numero de Telefono",
        isInverted : true,
        x : 477.5,
        y : 389,
        len : 6,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "personRequestingPhoneExtension",
        type : "boxes",
        text : "Numero de extension de Telefono",
        isInverted : true,
        x : 522,
        y : 389,
        len : 4,
        space : 9,
        size : 8,
    },// DataTypes.STRING,
    {
        key: "personRequestingCellphone",
        type : "text",
        text : "Celular",
        x : 442,
        y : 408,
    },// DataTypes.STRING,
    {
        key: "ServiceRequesting",
        type : "text",
        text : "Servicio que solicita la referencia",
        x : 193,
        y : 407,
    },// DataTypes.STRING,
    {
        key: "ServiceReferenceRequested",
        type : "text",
        text : "Servicio para el cual se solicita la referencia",
        x : 228,
        y : 417,
    },// DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "INFORMACIÓN CLÍNICA RELEVANTE",
    //     cols : 12, 
    // },
    {
        key: "relevantClinicalInformation",
        type : "textarea",
        text : "Diligenciar informacion",
        x : 69,
        y : 469,
        cols : 12,
        interline : 21,
        limitLines : 10,
        limitText : 100
    },// DataTypes.TEXT,
    // {
    //     key: "professionalSignature",
    //     type : "select",
    //     text : "Firma Profesional que remite",
    //     itemText : "name",
    //     itemValue : "id",
    //     list : "listDigitalSignature",
    // },// DataTypes.STRING,
    {
        key: "professionalRegistrationNumber",
        type : "text",
        text : "Numero de Registro del Profesional",
        x : 316,
        y: 739,
    },// DataTypes.STRING
]