module.exports = [
    // {
    //     key : "AttentionId",
    //     type : "number", // string
    //     text : "Numbero de Atencion",  
    // },

    // Furip = {
// UserId: DataTypes.INTEGER,
    // {
    //     type : "title",
    //     text : "PARTE A",
    //     cols : 12, 
    // },
    // {
    //     type : "title",
    //     text : "PRESTADORES DE SERVICIOS DE SALUD - FURIPS",
    //     cols : 12, 
    // },
    // //partA
    {
        key : "dateFiled",
        type: "boxes",
        text : "Fecha Radicacion",
        x : 126, 
        y : 133,
        len : 8,
        space : 11.5,
        size : 7,
        isSplitDateForm1 : true,
    }, //DataTypes.STRING,
    {
        key : "rg",
        type: "select",
        text : "RG",        
        itemText : "name",
        itemValue : "key",
        option : {
            si : { key : "si", name :"NIT", x : 254, y: 134 , w: 8, h : 8},
            no : { key : "no", name :"CC", x : 254, y: 134 , w: 8, h : 8},
        }
    }, //DataTypes.STRING,
    {
        key : "previousFiledNumber",
        type: "text",
        text : "Numero Radicacion Anterior",
        x : 150,
        y : 150,
        size : 8,        
    }, //DataTypes.STRING,
    {
        key : "filedNumber",
        type: "text",
        text : "Numero Radicado",
        x : 368,
        y : 134,
        size : 8,      
    }, //DataTypes.STRING,
    {
        key : "billNumber",
        type: "text",
        text : "Numero Factura",
        x : 368,
        y : 150,
        size : 8,      
    }, //DataTypes.STRING,
    // //provider
    // {
    //     type: "title",
    //     text : "I. DATOS DE LA INSTITUCIÓN PRESTADORA DE SERVICIOS DE SALUD",
    //     cols : 12,
    // },
    {
        key : "providerBusinessName",
        type: "text",
        text : "Razon Social Proveedor",
        x : 115,
        y : 173,
        size : 8,    
    }, //DataTypes.STRING,
    {
        key : "providerEnablementCode",
        type: "boxes",
        text : "Codigo Habilitacion",
        isInverted : true,
        x : 239, 
        y : 188,
        len : 11,
        space : 11.5,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "providerNit",
        type: "boxes",
        text : "NIT Prestador",
        isInverted : true,
        x : 526, 
        y : 188,
        len : 11,
        space : 11.6,
        size : 8
    }, //DataTypes.STRING,
    // //victim
    // {
    //     type : "title",
    //     text : "II. DATOS DE LA VICTIMA DEL EVENTO CATASTRÓFICO O ACCIDENTE DE TRANSITO",
    //     cols : 12,
    // },
    {
        key : "victimLastName",
        type: "text",
        text : "1er Apellido Victima",
        x : 308, 
        y : 214,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimSecondSurname",
        type: "text",
        text : "2do Apellido Victima",
        x : 58, 
        y : 214,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimFirstName",
        type: "text",
        text : "1er Nombre Victima",
        x : 58, 
        y : 236,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimSecondName",
        type: "text",
        text : "2do. Nombre Victima",
        x : 308, 
        y : 236,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimTypeId",
        type: "select",
        text : "Tipo de Documento Victima",
        itemText : "name",
        itemValue : "key",
        option : {
            cc : { key : "cc", name :"CC", x : 138, y : 253, w : 5, h : 4.3 },
            ce : { key : "ce", name :"CE", x : 149, y : 253, w : 5, h : 4.3 },
            pa : { key : "pa", name :"PA", x : 161, y : 253, w : 5, h : 4.3 },
            ti : { key : "ti", name :"TI", x : 173, y : 253, w : 5, h : 4.3 },
            rc : { key : "rc", name :"RC", x : 184, y : 253, w : 5, h : 4.3 },
            as : { key : "as", name :"AS", x : 195, y : 253, w : 5, h : 4.3 },
            ms : { key : "ms", name :"MS", x : 206, y : 253, w : 5, h : 4.3 },
            cd : { key : "cd", name :"CD", x : 217, y : 253, w : 5, h : 4.3 },
        }
        
    }, //DataTypes.STRING,
    {
        key : "victimNumberId",
        type: "boxes",
        text : "Numero Documento Victima",
        isInverted : true,
        x : 481, 
        y : 257,
        len : 11,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimBirthDate",
        type: "boxes",
        text : "Fecha de Nacimiento",
        isSplitDateForm1 : true,
        x : 139.5, 
        y : 270,
        len : 7,
        space : 11.5,
        size : 7
    }, //DataTypes.STRING,
    {
        key : "victimGender",
        type: "select",
        text : "Sexo",
        itemText : "name",
        itemValue : "key",
        option : {
           f1 : { key : "f", name :"F", x : 285, y : 267, w : 5, h : 4.3 },
           f : { key : "m", name :"M" , x : 311, y : 267, w : 5, h : 4.3 },
        }
    }, //DataTypes.STRING,
    {
        key : "victimAddress",
        type: "fieldText",
        text : "Direccion Residencia",       
        x : 132.5, 
        y : 287.5,
        w : 401,
        h : 11.5,        
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimState",
        type: "fieldText",
        text : "Departamento",
        x : 110, 
        y : 302,
        w : 181.5,
        h : 11.5,        
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimStateCode",
        type: "boxes",
        text : "Codigo Departamento",
        isInverted : true,
        x : 371, 
        y : 300,
        len : 1,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimCity",
        type: "fieldText",
        text : "Municipio",
        x : 110, 
        y : 316.5,
        w : 208,
        h : 11.5,        
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimCityCode",
        type: "boxes",
        text : "Codigo Municipio",
        isInverted : true,
        x : 383, 
        y : 315,
        len : 7,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimPhone",
        type: "boxes",
        text : "Telefono",
        isInverted : true,
        x : 527, 
        y : 300,
        len : 8,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key : "victimConditionInjured",
        type: "select",
        text : "Codicion del Accidentado",
        itemText : "name",
        itemValue : "key",
        option : {
            conductor1 : { key : "conductor", name :"Conductor", x : 160.5, y : 323.5, w : 5, h : 4.3 },
            peaton : { key : "peaton", name :"Peaton", x : 239.5, y : 323.5, w : 5, h : 4.3 },
            ocupante : { key : "ocupante", name :"Ocupante", x : 321.5, y : 323.5, w : 5, h : 4.3 },
            conductor : { key : "ciclista", name :"Ciclista", x : 421.5, y : 323.5, w : 5, h : 4.3 },
        }
    }, //DataTypes.STRING,
    // //site of accident
    // {
    //     type : "title",
    //     text : "III. DATOS DEL SITIO DONDE OCURRIÓ EL EVENTO CATASTRÓFICO O EL ACCIDENTE DE TRANSITO",
    //     cols : 12,
    // },
    // {
    //     type : "title",
    //     text : "Datos del sitio donde ocurrio el Evento Catastrofico",
    // },
    {
        key:"siteAccidentNatureOfEvent",
        type : "select",
        text : "Naturaleza del evento",
        itemText : "name",
        itemValue : "key",
        option : {
            "accidente-transito" : { key : "accidente-transito", name :"Accidente de Transito", x : 171.5, y : 351.5, w : 5, h : 4.3 },
            "sismo" : { key : "sismo", name :"Sismo", x : 171.5, y : 363, w : 5, h : 4.3 },
            "inundaciones" : { key : "inundaciones", name :"Inundaciones", x : 171.5, y : 376.5, w : 5, h : 4.3 },
            "rayo" : { key : "rayo", name :"Rayo", x : 171.5, y : 388.5, w : 5, h : 4.3 },
            "explosion" : { key : "explosion", name :"Explosion", x : 171.5, y : 402, w : 5, h : 4.3 },
            "incendio" : { key : "incendio", name :"Incendio", x : 171.5, y : 414.2, w : 5, h : 4.3 },
            
            "maremoto" : { key : "maremoto", name :"Maremoto", x : 273.2, y : 363, w : 5, h : 4.3 },
            "avalancha" : { key : "avalancha", name :"Avalancha", x : 273.2, y : 376.5, w : 5, h : 4.3 },
            "vendaval" : { key : "vendaval", name :"Vendaval", x : 273.2, y : 388.5, w : 5, h : 4.3 },
            "masacre" : { key : "masacre", name :"Masacre", x : 273.2, y : 402, w : 5, h : 4.3 },
            "ataque-municipios" : { key : "ataque-municipios", name :"Ataque a Municipios", x : 273.2, y : 414.2, w : 5, h : 4.3 },

            "erupciones-volcanicas" : { key : "erupciones-volcanicas", name :"Erupciones Volcanicas", x : 383, y : 363, w : 5, h : 4.3 },
            "deslizamiento-tierra" : { key : "deslizamiento-tierra", name :"Deslizamiento de Tierra", x : 383, y : 376.5, w : 5, h : 4.3 },
            "tornado" : { key : "tornado", name :"Tornado", x : 383, y : 388.5, w : 5, h : 4.3 },
            "mina-antipersonal"  : { key : "mina-antipersonal", name :"Mina Antipersonal", x : 383, y : 402, w : 5, h : 4.3 },
            
            "huracan" : { key : "huracan", name :"Huracan", x : 481.2, y : 363, w : 5, h : 4.3 },
            "incendio-natural" : { key : "incendio-natural", name :"Incendio Natural", x : 481.2, y : 376.5, w : 5, h : 4.3 },
            "combate" : { key : "combate", name :"Combate", x : 481.2, y : 402, w : 5, h : 4.3 },
            "otro" : { key : "otro", name :"Otro", x : 70.5, y : 426.3, w : 5, h : 4.3 },
        }
    }, //DataTypes.STRING,
    {
        key:"siteAccidentWhichOther",
        type : "fieldText",
        text : "Cual?",
        x : 110, 
        y : 429.6,
        w : 292,
        h : 9.4,        
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentOccurrenceAddress",
        type : "fieldText",
        text : "Direccion de la ocurrencia",
        x : 145, 
        y : 444.7,
        w : 390,
        h : 11.8,        
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentAccidentDate",
        type : "boxes",
        text : "Fecha Event/Accidente",
        isSplitDateForm1 : true,
        x : 151.5, 
        y : 454,
        len : 7,
        space : 11,
        size : 7
    }, //DataTypes.STRING,
    {
        key:"siteAccidentAccidentTime",
        type : "boxes",
        text : "Hora",
        isSplitHourForm1 : true,        
        x : 325, 
        y : 454,
        len : 3,
        space : 12,
        size : 7
    }, //DataTypes.STRING,
    {
        key:"siteAccidentState",
        type : "fieldText",
        text : "Departamento",
        x : 110, 
        y : 473,
        w : 182,
        h : 11.2,        
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentStateCode",
        type : "boxes",
        text : "Codigo Departamento",
        isInverted : true,
        x : 371, 
        y : 470.8,
        len : 1,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentCity",
        type : "fieldText",
        text : "Municipio",
        x : 110, 
        y : 487.2,
        w : 208,
        h : 11.2,        
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentCityCode",
        type : "boxes",
        text : "Codigo de Municipio",
        isInverted : true,
        x : 383, 
        y : 486,
        len : 2,
        space : 12,
        size : 8
    }, //DataTypes.STRING,
    {
        key:"siteAccidentZone",
        type : "select",
        text : "Zona",
        itemText : "name",
        itemValue : "key",
        option : {
            urbana :  { key : "urbana", name :"U", x : 444.7, y : 481.3, w : 5, h : 4.3},
            rural : { key : "rural", name :"R", x : 469.8, y : 481.3, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    {
        key:"siteAccidentAccidentDescription",
        type : "textarea",
        text : "Descripcion breve  del Evento/Acciendente (pricipales caracteristicas)",
        x : 50,
        y : 518,
        interline : 9,
        limitLines : 2,
        limitText : 110
    }, //DataTypes.STRING,

    // //vehicle of accident
    // {
    //     type : "title",
    //     text : "IV. DATOS DEL VEHICULO DE ACCIDENTE DE TRANSITO",
    //     cols : 12,
    // },
    {
        key:"vehicleAccidentVehicleType",
        type : "select",
        text : "Tipo de Vehiculo",
        itemText : "name",
        itemValue : "key",
        option : {
            "asegurado1": { key : "asegurado", name :"Asegurado" , x : 183, y : 555, w : 5, h : 4.3},
            "no-asegurado" :{ key : "no-asegurado", name :"No Asegurado" , x : 250.7, y : 555, w : 5, h : 4.3},
            "vehiculo-fantasma" : { key : "vehiculo-fantasma", name :"Vehiculo fantasma" , x : 334.6, y : 555, w : 5, h : 4.3},
            "poliza-falsa" : { key : "poliza-falsa", name :"Poliza Falsa" , x : 382.8, y : 555, w : 5, h : 4.3},
            "vehiculo-fuga" : { key : "vehiculo-fuga", name :"Vehiculo en fuga", x : 457, y : 555, w : 5, h : 4.3},
        }
        
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentBrand",
        type : "text",
        text : "Marca",
        x : 70,
        y : 571,
        size : 8,
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentPlate",
        type : "boxes",
        text : "Placa",
        isInverted : true,
        x : 433.5, 
        y : 571,
        len : 5,
        space : 13,
        size : 8
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentServiceType",
        type : "select",
        text : "Tipo de servicio",
        itemText : "name",
        itemValue : "key",
        option : {
            "particular" : { key : "particular", name :"Particular", x : 148.9, y : 583, w : 5, h : 4.3},
            "publico": { key : "publico", name :"Publico", x : 205.2, y : 583, w : 5, h : 4.3},
            "oficial": { key : "oficial", name :"Oficial", x : 250.5, y : 583, w : 5, h : 4.3},
            "vehiculo-emergencia" : { key : "vehiculo-emergencia", name :"Vehiculo de emergencia", x : 358.6, y : 583, w : 5, h : 4.3},
            "vehiculo-diplomatico-o-consular" : { key : "vehiculo-diplomatico-o-consular", name :"Vehiculo de servicio", x : 503.6, y : 583, w : 5, h : 4.3},
            "vehiculo-transporte-masivo" : { key : "vehiculo-transporte-masivo", name :"Vehiculo de transporte masivo", x : 205.2, y : 596.5, w : 5, h : 4.3},
            "vehiculo-escolar" : { key : "vehiculo-escolar", name :"Vehiculo escolar", x : 346.7, y : 596.5, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentInsuranceCode",
        type : "boxes",
        text : "Codigo de la aseguradora",
        isInverted : true,
        x : 182.5, 
        y : 612,
        len : 5,
        space : 11.5,
        size : 8
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentPolicyNumber",
        type : "boxes",
        text : "Numero de la Poliza",
        isInverted : true,
        x : 321.5, 
        y : 626,
        len : 19,
        space : 12.5,
        size : 8
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentValidSince",
        type : "boxes",
        text : "Vigencia desde",
        isSplitDateForm1 : true,        
        x : 106, 
        y : 638,
        len : 7,
        space : 11.2,
        size : 7
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentValidUntil",
        type : "boxes",
        text : "Hasta",
        isSplitDateForm1 : true,        
        x : 218, 
        y : 638,
        len : 7,
        space : 11.7,
        size : 7
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentAuthorityIntervention",
        type : "select",
        text : "Intervencion de autoridad",
        itemText : "name",
        itemValue : "key",
        option : {
            si :{ key : "si", name :"Si", x : 481.3, y : 624, w : 5, h : 4.3},
            no : { key : "no", name :"No", x : 526, y : 624, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    {
        key:"vehicleAccidentPolicySurplusCharge",
        type : "select",
        text : "Cobro Excedente Poliza",
        itemText : "name",
        itemValue : "key",
        option : {
            si :{ key : "si", name :"Si", x : 481, y : 638.7, w : 5, h : 4.3},
            no :{ key : "no", name :"No", x : 526, y : 638.7, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,

    // {
    //     type : "title",
    //     text  : "V. DATOS DEL PROPIETARIO DEL VEHÍCULO",
    //     cols : 12
    // },
    // //vehicle owner
    { 
        key : "vehicleOwnerLastName",
        type : "text",
        text : "1er Apellido o Razon Social",
        x : 58,
        y: 667,
        size : 8,
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerSecondSurname",
        type : "text",
        text : "2do Apellido",
        x : 308,
        y: 667,
        size : 8
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerFirstName",
        type : "text",
        text : "1er Nombre",
        x : 58,
        y: 687,
        size : 8,
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerSecondName",
        type : "text",
        text : "2do Nombre",
        x : 308,
        y: 687,
        size : 8,
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option : {
            cc : { key : "cc", name :"CC", x : 137.7, y : 704, w : 5, h : 4},
            ce : { key : "ce", name :"CE", x : 149, y : 704, w : 5, h : 4},
            pa : { key : "pa", name :"PA", x : 160.5, y : 704, w : 5, h : 4},
            ti : { key : "ti", name :"TI", x : 172, y : 704, w : 5, h : 4},
            rc : { key : "rc", name :"RC", x : 183, y : 704, w : 5, h : 4},
            cd : { key : "cd", name :"CD", x : 194.3, y : 704, w : 5, h : 4},
        }
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted : true,
        x : 526, 
        y : 708,
        len : 15,
        space : 11.5,
        size : 8
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerAddress",
        type : "fieldText",
        text : "Direccion de Residencia",
        x : 133, 
        y : 724.2,
        w : 400.8,
        h : 11.8,        
        size : 8
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerState",
        type : "fieldText",
        text : "Departamento",
        x : 121.5, 
        y : 736.2,
        w : 185.3,
        h : 9.5,        
        size : 8
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerStateCode",
        type : "boxes",
        text : "Codigo departamento",
        isInverted : true,
        x : 359, 
        y : 734,
        len : 1,
        space : 12,
        size : 8,
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerCity",
        type : "fieldText",
        text : "Municipio",
        x : 121.5, 
        y : 747.2,
        w : 185.3,
        h : 9.5,        
        size : 8
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerCityCode",
        type : "boxes",
        text : "Codigo de Municipio",
        isInverted : true,
        x : 444.5, 
        y : 746,
        len : 2,
        space : 12,
        size : 8,
    },
    // // DataTypes.STRING,
    { 
        key : "vehicleOwnerPhone",
        type : "boxes",
        text : "Telefono",
        isInverted : true,
        x : 525.8, 
        y : 734,
        len : 9,
        space : 11.5,
        size : 8,
    },
    // // DataTypes.STRING,
    
    { 
        key : "partATotalFolio",
        type : "boxes",
        text : "Total Folios",
        isInverted : true,
        x : 526.8, 
        y : 758,
        len : 2,
        space : 11.8,
        size : 6,
    }, 

    {
        key : "otherPagePdf",
        keyPage : 1,
    },
    // //DataTypes.STRING,

    //     //PartB
    // {
    //     type : "title",
    //     text : "Parte B",
    //     cols : 12
    // },
    // // Driver Vehicle
    // {
    //     type : "title",
    //     text : "VI. DATOS DEL CONDUCTOR DEL VEHÍCULO INVOLUCRADO EN EL ACCIDENTE DE TRANSITO",
    //     cols : 12,
    // },
    { 
        key: "driverVehicleLastName",
        type : "text",
        text : "1er Apellido",
        x : 60,
        y : 157,
        size : 6,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleSecondSurname",
        type : "text",
        text : "2do Apellido",
        x : 330,
        y : 157,
        size : 6,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleFirstName",
        type : "text",
        text : "1er Nombre",
        x : 60,
        y : 177,
        size : 6,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleSecondName",
        type : "text",
        text : "2do Nombre",
        x : 330,
        y : 177,
        size : 6,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option : {
            cc: { key : "cc", name :"CC", x : 150, y : 196.3, w : 4.5, h : 3.8},
            ce: { key : "ce", name :"CE", x : 162.2, y : 196.3, w : 4.5, h : 3.8},
            pa: { key : "pa", name :"PA", x : 175, y : 196.3, w : 4.5, h : 3.8},
            ti: { key : "ti", name :"TI", x : 187.8, y : 196.3, w : 4.5, h : 3.8},
            rc: { key : "rc", name :"RC", x : 200.4, y : 196.3, w : 4.5, h : 3.8},
            as: { key : "as", name :"AS", x : 213.1, y : 196.3, w : 4.5, h : 3.8},
            cd: { key : "cd", name :"CD", x : 225.6, y : 196.3, w : 4.5, h : 3.8},
        }
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted : true,
        x : 521.5, 
        y : 200,
        len : 15,
        space : 10.9,
        size : 8,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleAddress",
        type : "fieldText",
        text : "Direccion de Residencia",
        x : 145.8, 
        y : 216.2,
        w : 382.5,
        h : 11.2,        
        size : 8
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleState",
        type : "fieldText",
        text : "Departamento",
        x : 132.8, 
        y : 230.8,
        w : 195,
        h : 10.5,        
        size : 8
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleStateCode",
        type : "boxes",
        text : "Codigo de Departamento",
        isInverted : true,
        x : 373, 
        y : 229,
        len : 1,
        space : 11,
        size : 8,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleCity",
        type : "fieldText",
        text : "Municipio Residencia",
        x : 132.8, 
        y : 244.8,
        w : 195,
        h : 10.5,        
        size : 8
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehicleCityCode",
        type : "boxes",
        text : "Codigo Municipio",
        isInverted : true,
        x : 445.8, 
        y : 243,
        len : 2,
        space : 10.5,
        size : 8,
    }, 
    // //DataTypes.STRING,
    { 
        key: "driverVehiclePhone",
        type : "boxes",
        text : "Telefono",
        isInverted : true,
        x : 521.2, 
        y : 229,
        len : 9,
        space : 10.8,
        size : 8,
    }, 
    // //DataTypes.STRING,
    // // Remision
    // {
    //     type : "title",
    //     text : "VII. DATOS DE REMISION",
    //     cols : 12,
    // },
    {
        key : "referralType",
        type : "select",
        text : "Tipo de Refencia",
        itemText : "name",
        itemValue : "key",
        option : {
            "remision1" : { key  :"remision", name : "Remision", x : 174.9, y : 262.7, w : 5, h : 4.3},
            "orden-servicio" : { key  :"orden-servicio", name : "Orden de Servicio", x : 276, y : 262.3, w : 5, h : 4.3},
        }
    },// DataTypes.STRING,
    {
        key : "referralDate",
        type : "boxes",
        text : "Fecha remision",   
        isSplitDateForm1 : true,             
        x : 140.1, 
        y : 277,
        len : 7,
        space : 12.7,
        size : 7,
    },// DataTypes.STRING,
    {
        key : "referralTime",
        type : "boxes",
        text : "Hora remision",     
        isSplitHourForm1 : true,                   
        x : 266.8, 
        y : 277,
        len : 4,
        space : 12,
        size : 7,
    },// DataTypes.STRING,
    {
        key : "referralProviderName",
        type : "text",
        text : "Prestador que remite",
        x : 134.8,
        y : 293,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "referralProviderInscriptionCode",
        type : "boxes",
        text : "Codigo de inscripcion",
        isInverted : true,
        x : 276, 
        y : 307,
        len : 11,
        space : 12.9,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "referralProviderProfessional",
        type : "text",
        text : "Profesional que remite",
        x : 134.8,
        y : 319.8,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "referralProviderProfessionalPosition",
        type : "text",
        text : "Cargo profesional",
        x : 381.8,
        y : 319.8,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "acceptanceDate",
        type : "boxes",
        text : "Fecha aceptacion",        
        isSplitDateForm1 : true,
        x : 140.8, 
        y : 331,
        len : 7,
        space : 12.5,
        size : 7,
    },// DataTypes.STRING,
    {
        key : "acceptanceTime",
        type : "boxes",
        text : "Hora aceptacion",
        isSplitHourForm1 : true,        
        x : 267, 
        y : 331,
        len : 3,
        space : 12,
        size : 7,
    },// DataTypes.STRING,
    {
        key : "acceptanceProviderName",
        type : "text",
        text : "Prestador que recibe",
        x : 134.8, 
        y : 345.8,                
        size : 8
    },// DataTypes.STRING,
    {
        key : "acceptanceProviderInscriptionCode",
        type : "boxes",
        text : "Codigo de inscripcion",
        isInverted : true,
        x : 275.7, 
        y : 358.5,
        len : 11,
        space : 12.5,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "acceptanceProviderProfessional",
        type : "text",
        text : "Professional que recibe",
        x : 134.5, 
        y : 370.5,
        size : 8,
    },// DataTypes.STRING,
    {
        key : "acceptanceProviderProfessionalPosition",
        type : "text",
        text : "Cargo profesional",
        x : 381.8,
        y : 370.5,
        size : 8,
    },// DataTypes.STRING,

    // // Protection Mobilization Victim
    // {
    //     type : "title",
    //     text : "VIII. AMPARO DE TRANSPORTE Y MOVILIZACION DE LA VICTIMA",
    //     cols : 12
    // },
    {
        key: "protectionMobilizationVictimPlate",
        type : "boxes",
        text : "Placa No.",
        isInverted : true,
        x : 263, 
        y : 401,
        len : 5,
        space : 13,
        size : 8,
    },
    //  //DataTypes.STRING,
    {
        key: "protectionMobilizationVictimTransportVictimFrom",
        type : "text",
        text : "Transporto la victima desde",
        x : 135, 
        y : 417,
        size : 8,
    },
    //  //DataTypes.STRING,
    {
        key: "protectionMobilizationVictimTransportVictimSince",
        type : "text",
        text : "Hasta",
        x : 372, 
        y : 417,
        size : 8,
    },
    //  //DataTypes.STRING,
    {
        key: "protectionMobilizationVictimTransportationType",
        type : "select",
        text : "Tipo de Transporte",
        itemText : "name",
        itemValue : "key",
        option : {
            "ambulancia-basica" : { key : "ambulancia-basica", name : "Ambulancia Basica", x : 200.2, y : 429.3, w : 5, h : 4.3},
            "ambulancia-medicada" : { key : "ambulancia-medicada", name : "Ambulancia Medicada", x : 300.4, y : 429.3, w : 5, h : 4.3},
        }
    },
    //  //DataTypes.STRING,
    {
        key: "protectionMobilizationVictimPlace",
        type : "select",
        text : "Lugar donde recoge la Victima",
        itemText : "name",
        itemValue : "key",
        option : {
           urban: { key: "urban", name: "U", x : 456.7, y : 427.3, w : 5, h : 4.3},
           rural: { key: "rural", name: "R", x : 477.7, y : 427, w : 5, h : 4.3},
        }
    },
    //  //DataTypes.STRING,

    // // Certificate Medical Care Victim
    // {
    //     type : "title",
    //     text : "IX. CERTIFICADO DE LA ATENCIÓN MEDICA DELA VICTIMA COMO PRUEBA DEL ACCIDENTE O EVENTO",
    //     cols : 12,
    // },
    {
        key: "certificateMedicalCareVictimEntryDate",
        type : "boxes",
        text : "Fecha de Ingreso",
        isSplitDateForm1 : true,
        x : 114.3, 
        y : 453.7,
        len : 7,
        space : 12.7,
        size : 7,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEntryTime",
        type : "boxes",
        text : "a las",
        isSplitHourForm1 : true,        
        x : 253.5, 
        y : 453.7,
        len : 4,
        space : 13,
        size : 7,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimDiagnosesPrincipalCIE10",
        type : "boxes",
        text : "Codigo Diagnostico principal de Ingreso",
        x : 173.8, 
        y : 470,
        len : 3,
        space : 13,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimDiagnosesRelated1CIE10",
        type : "boxes",
        text : "Otro código Diagnóstico principal de Ingreso",
        x : 173.8, 
        y : 483.5,
        len : 3,
        space : 13,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimDiagnosesRelated2CIE10",
        type : "boxes",
        text : "Otro código Diagnóstico principal de Ingreso",
        x : 173.8, 
        y : 495.5,
        len : 3,
        space : 13,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEgressDate",
        type : "boxes",
        text : "Fecha de egreso",
        isSplitDateForm1 : true,
        x : 376, 
        y : 453.7,
        len : 7,
        space : 10.5,
        size : 6,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEgressTime",
        type : "boxes",
        text : "a las",
        isSplitHourForm1 : true,        
        x : 493, 
        y : 453.7,
        len : 4,
        space : 10.5,
        size : 6,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEgressDiagnosesPrincipalCIE10",
        type : "boxes",
        text : "Código Diagnóstico principal de Egreso",
        x : 435.2, 
        y : 470,
        len : 4,
        space : 10.5,
        size : 8,



    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEgressDiagnosesRelated1CIE10",
        type : "boxes",
        text : "Otro código Diagnóstico principal de Egreso",
        x : 435.2, 
        y : 483.5,
        len : 5,
        space : 10.5,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimEgressDiagnosesRelated2CIE10",
        type : "boxes",
        text : "Otro código Diagnóstico principal de Egreso",
        x : 435.2, 
        y : 495.5,
        len : 5,
        space : 10.5,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalLastName",
        type : "boxes",
        text : "1er Apellido del Medico o Profesional",
        x : 61, 
        y : 511.8,
        len : 18,
        space : 12.7,      
        size : 8
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalSecondSurname",
        type : "boxes",
        text : "2do Apellido del Medico o Profesional",
        x : 330.5, 
        y : 511.8,
        len : 18,
        space : 10.5,      
        size : 8
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalFirstName",
        type : "boxes",
        text : "1er Nombre del Medico o Profesional",
        x : 61, 
        y : 531,
        len : 18,
        space : 12.7,      
        size : 8
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalSecondName",
        type : "boxes",
        text : "2do Nombre del Medico o Profesional",
        x : 330.5, 
        y : 531,
        len : 18,
        space : 10.5,      
        size : 8
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option: {
            cc: { key : "cc", name: "CC", x : 150, y : 547, w : 4, h : 4.3},
            ce: { key : "ce", name: "CE", x : 164, y : 547, w : 4, h : 4.3},
            pa: { key : "pa", name: "PA", x : 177, y : 547, w : 4, h : 4.3},
        }
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted : true,
        x : 500, 
        y : 550.5,
        len : 11,
        space : 10.8,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimTreatingProfessionalMedRecord",
        type : "boxes",
        text : "Numero de registro medico",
        isInverted:true,
        x : 500.5, 
        y : 562,
        len : 11,
        space : 10.7,
        size : 8,
    }, // DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "X. AMPAROS QUE RECLAMA",
    //     cols : 12,
    // },
    {
        key: "certificateMedicalCareVictimSurgicalMedicalExpensesBilled",
        type : "text",
        text : "Total Gastos medicos quirurgicos",
        x : 200, 
        y : 593.5,
        size : 8,

    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimSurgicalMedicalExpensesFosyga",
        type : "text",
        text : "Valor reclamado Gastos medicos quirurgicos",
        x : 300, 
        y : 593.5,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimMobilizationExpensesBilled",
        type : "text",
        text : "Total Gastos de transporte y movilizacion de la victima",
        x : 200, 
        y : 602.5,
        size : 8,
    }, // DataTypes.STRING,
    {
        key: "certificateMedicalCareVictimMobilizationExpensesFosyga",
        type : "text",
        text : "Valor reclamado Gastos de transporte y movilizacion de la victima",
        x : 300, 
        y : 602.5,
        size : 8,
    }, // DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "XI. AMPAROS QUE RECLAMA",
    //     cols : 12,
    // },
    // // Provider Health
    { 
        key :"providerHealthName",
        type : "img-b64",
        text : "Nombre",
        x : 140,
        y : 675,
        w : 100,
        h : 15,
    },// DataTypes.STRING,
    { 
        key :"providerHealthSignature",
        type : "img-b64",
        text : "FIRMA DEL REPRESENTANTE LEGAL O GERENTE",
        list : "listDigitalSignatures",
        x : 405,
        y : 675,
        w : 100,
        h : 15,
    },// DataTypes.STRING,
  
]