module.exports =  [
    //UserId: DataTypes.INTEGER,
    // {
    //     type : "title",
    //     text : "FORMULARIO UNICO DE RECLAMACION DE GASTOS DE TRANSPORTE Y MOVILIZACION DE VICTIMAS - FURTRAN",
    //     cols : 12,
    // },
    // { 
    //     key : "AttentionId",
    //     type : "number",
    //     text : "Numero de Atencion",
    // }, //DataTypes.INTEGER,
    { 
        key : "deadline",
        type : "boxes",
        text : "Fecha de Entrega",
        x : 148, 
        y : 118,
        len : 7,
        space : 11.5,
        size : 6,
        isSplitDateForm1 : true,
    }, //DataTypes.STRING,
    { 
        key : "rg",
        type : "text",
        text : "RG",
        itemText : "name",
        itemValue : "key",
        keyCondition : "rg",
        x : 305, 
        y : 117.5,
        size : 6,  
        option: {
           si: { key : "si", name: "Si", x : 432, y : 130,  isText : true},
           no: { key : "no", name: "No",x : 432, y : 130,  isText : true},
        }
    }, //DataTypes.STRING,
    { 
        key : "previousFilingNumber",
        type : "text",
        text : "No. Radicado anterior(Marcar RG)",
        x : 139,
        y : 135,
        size : 8
    }, //DataTypes.STRING,
    { 
        key : "filingNumber",
        type : "text",
        text : "No Radicado",
        x : 385,
        y : 117.5,
        size : 8,
    }, //DataTypes.STRING,
    // {
    //     type: "title",
    //     text : "I. DATOS DEL TRANSPORTADOR(Si es persona natural diligenciar los campos referentes a nombre y apellidos)",
    //     cols : 12,
    // },
    { 
        key : "transporterName",
        type : "text",
        text : "Nombre Empresa de Transporte Especial o Reclamante",
        x : 212,
        y : 161.5,
        size : 7
    }, //DataTypes.STRING,
    { 
        key : "transporterEnableCode",
        type : "boxes",
        text : "Codigo de habilitacion Empresa de Transporte Especial",
        x : 213.4, 
        y : 173.3,
        len : 11,
        space : 11.7,
        size : 5,
    }, //DataTypes.STRING,
    { 
        key : "transporterLastName",
        type : "text",
        text : "1er Apellido",
        x : 80,
        y : 185,
        size : 7
    }, //DataTypes.STRING,
    { 
        key : "transporterSecondSurname",
        type : "text",
        text : "2do Apellido",
        x : 314,
        y : 185.5,
        size : 7
    }, //DataTypes.STRING,
    { 
        key : "transporterFirstName",
        type : "text",
        text : "1er Nombre",
        x : 80,
        y : 204.4,
        size : 7
    }, //DataTypes.STRING,
    { 
        key : "transporterSecondName",
        type : "text",
        text : "2do Nombre",
        x : 316,
        y : 204.4,
        size : 7
    }, //DataTypes.STRING,
    { 
        key : "transporterTypeId",
        type : "select",
        text : "Tipo de Documento",
        itemText : "name",
        itemValue : "key",
        option: {
            "cc" : { key : "cc", name: "CC", isText : true, text: "X", x : 152.5, y : 220, w : 5, h : 4.3},
            "ce" : { key : "ce", name: "CE", isText : true, text: "X", x : 164, y : 481.3, w : 5, h : 4.3},
            "pa" : { key : "pa", name: "PA", isText : true, text: "X", x : 176, y : 481.3, w : 5, h : 4.3},
            "nit" : { key : "nit", name: "NIT", isText : true, text: "X", x : 187, y : 220, size: 5, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    { 
        key : "transporterNumberId",
        type : "boxes",
        text : "Numero de Documento",
        isInverted:true,
        x : 411, 
        y : 220,
        len : 12,
        space : 11.6,
        size : 5,
    }, //DataTypes.STRING,
    { 
        key : "transporterServiceType",
        type : "select",
        text : "Tipo de Servicio",
        itemText : "name",
        itemValue : "key",
        option: {
            "ambulancia-basica":{ key : "ambulancia-basica", name: "Ambulancia Basica", x : 226 , y : 231.3, w: 3.5, h: 3.5 },
            "ambulancia-medicada":{ key : "ambulancia-medicada", name: "Ambulancia Medicada", x : 318 , y : 231.3, w: 3.5, h: 3.5},
        }
    }, //DataTypes.STRING,
    { 
        key : "transporterPersonServiceType",
        type : "select",
        text : "Si es persona Natural-tipo Servicio",
        itemText : "name",
        itemValue : "key",
        option: {
            "particular": { key : "particular", name: "Particular",  x : 226 , y : 244.3, w: 3.5, h: 3.5},
            "vehiculo-masivo": { key : "vehiculo-masivo", name: "Vehiculo de transporte masico", x : 226 , y : 257.6, w: 3.5, h: 3.5},
            "publico": { key : "publico", name: "Publico", x : 318 , y : 244.4, w: 3.5, h: 3.5},
            "vehiculo-escolar": { key : "vehiculo-escolar", name: "Vehiculo escolar", x : 318 , y : 257.6, w: 3.5, h: 3.5},
            "oficial": { key : "oficial", name: "Oficial", x : 364.1 , y : 244.4, w: 3.5, h: 3.5},
            "otro": { key : "otro", name: "Otro", x : 364.1 , y : 257.5, w: 3.5, h: 3.5},
            "vehiculo-diplomatico-consular": { key : "vehiculo-diplomatico-consular", name: "Publico", x : 514 , y : 244.4, w: 3.5, h: 3.5},
        }
    }, //DataTypes.STRING,
    {
        key : "transporterPersonWhich",
        type : "text",
        text : "Cual (En caso otro)",
        x : 407,
        y : 257.5,
        size : 7,
    },
    { 
        key : "transporterPlate",
        type : "boxes",
        text : "En vehiculo con placa No",
        x : 142.5, 
        y : 271.5,
        len : 5,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterAddress",
        type : "text",
        text : "Direccion de la empresa o persona que realiza el transporte",
        x : 223, 
        y : 284.6,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterPhone",
        type : "boxes",
        text : "Telefono o celular",
        x : 130, 
        y : 298,
        len : 13,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterStateName",
        type : "text",
        text : "Departamento",
        x : 127, 
        y : 311,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterStateCode",
        type : "boxes",
        text : "Codigo Departamento",
        x : 478.5, 
        y : 311,
        len : 1,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterCityName",
        type : "text",
        text : "Municipio",
        x : 127, 
        y : 324,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transporterCityCode",
        type : "boxes",
        text : "Codigo Municipio",
        x : 478.5, 
        y : 324.5,
        len : 13,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "II. RELACION DE VICTIMAS TRANSLADADAS",
    //     cols : 12,
    // },
    { 
        key : "transferredVictimsTypeId",
        type : "select",
        text : "tipo de Documento permitido",
        itemText : "name",
        itemValue : "key",
        option: {
            "cc": { key : "particular", isText : true, text: "X", name: "Particular", size: 5, x : 139 , y : 346.5, w: 3.5, h: 3.5},
            "ce": { key : "vehiculo-masivo", name: "Vehiculo de transporte masico", size: 5, isText : true, text: "X", x : 153 , y : 346.5, w: 3.5, h: 3.5},
            "pa": { key : "publico", name: "Publico", isText : true, text: "X",size: 5, x : 164 , y : 346.5, w: 3.5, h: 3.5},
            "ti": { key : "vehiculo-escolar", name: "Vehiculo escolar", isText : true, text: "X", size: 5, x : 176 , y : 346.5, w: 3.5, h: 3.5},
            "as": { key : "oficial", name: "Oficial", isText : true, text: "X", size: 5, x : 364.1 , y : 187, w: 3.5, h: 3.5},
            "ms": { key : "otro", name: "Otro", isText : true, text: "X", size: 5, x : 198.8 , y : 346.5, w: 3.5, h: 3.5},
            
        }
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsNumberId",
        type : "text",
        text : "",
        x : 91, 
        y : 369.3,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsFirstName",
        type : "text",
        text : "",
        x : 176.5, 
        y : 369.3,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsSecondName",
        type : "text",
        text : "",
        x : 269, 
        y : 369.3,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsLastName",
        type : "text",
        text : "",
        x : 361, 
        y : 369.3,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsSecondSurname",
        type : "text",
        text : "",
        x : 453, 
        y : 369.3,
        size : 6,
    }, //DataTypes.STRING, */
    { 
        key : "transferredVictimsEventType",
        type : "select",
        text : "Tipo de evento que sucita la movilizacion",
        itemText : "name",
        itemValue : "key",
        option : {
            "accidente-transito" : { key : "accidente-transito", name : "Accidente de transito", x : 236.5, y : 434.5, w : 5, h : 4.3},
            "evento-catastrofico" : { key : "evento-catastrofico", name : "Evento catastrofico", x : 328.8, y : 434.5, w : 5, h : 4.3},
            "evento-terrorista" : { key : "evento-terrorista", name : "Evento terrorista", x : 397.9, y : 434.5, w : 5, h : 4.3},
            "otro": { key : "otro", name : "Otro", x : 444, y : 434.5, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    { 
        key : "transferredVictimsEventOthers",
        type : "text",
        text : "Descripcion del otro evento",
        x : 139, 
        y : 446.3,
        size : 6,
    }, //DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "III. LUGAR EN EL QUE SE RECOGE LA VICTIMA O VICTIMAS",
    //     cols : 12,
    // },
    { 
        key : "pickUpPlaceAddress",
        type : "text",
        text : "Direccion",
        x : 105, 
        y : 470.3,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "pickUpPlaceStateName",
        type : "text",
        text : "Departamento",
        x : 105, 
        y : 483.2,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "pickUpPlaceStateCode",
        type : "boxes",
        text : "Codigo Departamento",
        x : 375.2, 
        y : 482.7,
        len : 1,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "pickUpPlaceCityName",
        type : "text",
        text : "Municipio",
        x : 105, 
        y : 495.5,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "pickUpPlaceCityCode",
        type : "boxes",
        text : "Codigo Municipio",
        x : 375, 
        y : 495.5,
        size : 6,
        len : 2,
        space : 11.8,
        size : 6,
    }, //DataTypes.STRING,
    { 
        key : "pickUpPlaceZone",
        type : "select",
        text : "Zona",
        itemText : "name",
        itemValue : "key",
        option : {
           "urban": { key : "urban", name : "U" , x : 456.3, y : 482, w : 5, h : 4.3},
           "rural" : { key : "rural", name : "R", x : 479.1, y : 482, w : 5, h : 4.3},
        }
    }, //DataTypes.STRING,
    // {
    //     type : "title",
    //     text : "IV. CERTIFICACION DE TRANSLADO DE VICTIMAS",
    //     cols : 12,
    // },
    { 
        key : "certificationDate",
        type : "boxes",
        text : "El dia",
        action : "setDate",
        x : 98.5, 
        y : 525,
        len : 7,
        space : 11.9,
        size : 6,
        isSplitDateForm1 : true,
    }, //DataTypes.STRING,
    { 
        key : "certificationTime",
        type : "boxes",
        text : "A las",
        action : "setDate",
        x : 240, 
        y : 525,
        len : 3,
        space : 11.6,
        size : 6,
        isSplitHourForm1 : true,        

    }, //DataTypes.STRING,
    { 
        key : "certificationCenterName",
        type : "text",
        text : "Nombre IPS que atendio la victima",
        x : 153, 
        y : 535.8,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterNit",
        type : "boxes",
        text : "NIT",
        x : 107.5, 
        y : 545.5,
        len : 10,
        space : 11.6,
        size : 6,

    }, //DataTypes.STRING,
    { 
        key : "certificationCenterCode",
        type : "boxes",
        text : "Codigo IPS",
        isInverted : true,
        x : 525.1, 
        y : 546,
        len : 10,
        space : 11.6,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterAddress",
        type : "text",
        text : "Direccion",
        x : 104, 
        y : 556.8,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterStateName",
        type : "text",
        text : "Departamento",
        x : 104, 
        y : 567.2,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterStateCode",
        type : "boxes",
        text : "Codigo Departamento",
        x : 363.1, 
        y : 567.2,
        len : 1,
        space : 11.6,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterCityName",
        type : "text",
        text : "Municipio",
        x : 104, 
        y : 577.3,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterCityCode",
        type : "boxes",
        text : "Codigo de Municipio",
        x : 397.8, 
        y : 577.3,
        len : 2,
        space : 11.6,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterPhone",
        type : "boxes",
        text : "Telefono",
        x : 432.4, 
        y : 567.2,
        len : 8,
        space : 11.6,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterManagerName",
        type : "img-b64",
        text : "Nombre del representante legar o persona responsable para tramite de admisiones de la IPS",
        x : 316, 
        y : 619.2,
        w : 20,
        h : 10,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterManagerSignature",
        type : "text",
        text : "Firma del representante legar o persona responsable  para tramite de admisiones de la IPS",
        itemText : "name",
        itemValue : "id",
        list : "listDigitalSignature",
        x : 106, 
        y : 619.2,
        w : 20,
        h : 10,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterManagerTypeId",
        type : "text",
        text : "Tipo de Documento",
        itemText : "description",
        itemValue : "name",
        global_list : "typeIds",
        x : 442, 
        y : 619.2,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationCenterManagerNumberId",
        type : "text",
        text : "Numero de Documento",
        x : 465, 
        y : 619.2,
        size : 7,
    }, //DataTypes.STRING,
    { 
        key : "certificationTransporterSignature",
        type : "img-b64",
        text : "Firma del representante legal de la empres transportadora o de la persona natural que realizo el transporte",
        x : 271, 
        y : 655,
        w : 20,
        h : 10,
    }, //DataTypes.STRING
]