export default {
    hello                               : "Hello",
    admissions                          : "Admissions",
    nursing                             : "Nursing",
    medico                              : "Medico",
    pharmacy                            : "Pharmacy",
    promotion_and_prevention            : "Promotion and prevention",
    specialized_services                : "Specialized services",
    eps                                 : "EPS",
    providers                           : "Providers",
    laboratories                        : "Laboratories",
    diagnostic_aids                     : "Diagnostic aids",
    outpatient_consultations            : "Outpatient consultations",
    non_pos_medications                 : "Non pos medications",
    management                          : "Management",
    administration                      : "Administration",
    billing                             : "Billing",
    manager                             : "Manager",
    audits                              : "Audits",
    systems                             : "Systems",
    urgency                             : "Urgency",
    dashboard_medico                    : "Medico",
    n_a                                 : "N. Atention",
    date                                : "Date",
    campus                              : "Campus",
    state                               : "State",
    document                            : "Document",
    patient                             : "Patient",
    actions                             : "Actions",              
    cedula                              : "Cedula",
    tarjet_id                           : "Tarjet ID",
    passport                            : "Passport",
    search                              : "Search",
    contact_name_keysi                  : "Keysi González Fernández",
    contact_tel                         : "Tel  : 315 465 2115 / 3665271", // 301 646 4330 / 301 460 2702
    contact_email                       : "Keysi2510@hotmail.com",
    contact_email1                      : "Ley-antitramite@hotmail.com",
    contact_address                     : "Oficina Kra 12 Calle 114 # 15-08" ,
    conctact_city                       : "Barranquilla - Atlantico",
    anti_procedure_law                  : "ILC-ASC ley anti tramite salud de los colombianos",
    mission                             : "Mission",
    organization_that_guarantees        : "We are an organization that guarantees to improve the conditions of the conventional health service, committed to ethics, respect for the environment and efficiency in the provision of care services in accordance with the standards issued by the WHO, World Health Organization, developing all actions related to mandatory compliance guidelines.",
    vision                              : "Vision",
    universal_platform                  : "In 2022, the 'ILC-ASC' App will be the universal platform for all health service providers at the national level, in order to finalize the lacking care processes, based on the anti-trafficking law standard.",
    law_enforcement                     : "ILC-ASC With Application of Law 019 of 2012",
    less_paper                          : "Less Paper",
    system_modeled_for                  : "System Modeled to require less paperwork and attend to patients in a timely manner",
    fewer_rows                          : "Fewer Rows",
    agile_and_efficient_platform        : "Agile and efficient platform with fast attention leaving behind the long lines of patients",
    specialist_on_time                  : "Specialist on time",
    attention_of_doctors                : "The attention of specialized doctors in less time, guarantees a diagnosis in time for its due Treatment",
    service                             : "Service",
    because_the_user                    : "Because the user deserves the best",
    landing                             : "Landing",
    some_screenshots                    : "Some Screenshots",
    contact                             : "Contact",
    send                                : "Send",
    login                               : "Login",
    logout                              : "Logout",
    start                               : "Start",
    description                         : "Description",
    screenshots                         : "Screenshots",
    contact                             : "Contact",
    contacts                            : "Contacts",
    register                            : "Register",
    name                                : "Name",
    email                               : "Email",
    message                             : "Message",
    username                            : "Username",
    password                            : "Password",
    forget_password                     : "Forget password",
    second_name                         : "Second name",
    second_surname                      : "Second surname",
    department                          : "Department",
    neighborhood                        : "Neighborhood",
    occupation                          : "Occupation",
    companion                           : "Companion",
    accompanying_name                   : "Accompanying name",
    sex                                 : "Sex",
    document_type                       : "Document type",
    lastname                            : "Lastname",
    gender                              : "Gender",
    phone                               : "Phone",
    cell_phone                          : "Cell phone",
    address                             : "Address",
    date_birth                          : "Date of Birth",
    age                                 : "Edad",
    eps_type                            : "EPS type",
    zone                                : "Zone",
    city                                : "City",
    other                               : "Other",
    father_name                         : "Father's name",
    father_lastname                     : "Father's last name",
    father_document                     : "Father's document",
    father_document_type                : "Father's document type",
    mother_name                         : "Mother's name",
    mother_surname                      : "Mother's Surname",
    mother_document                     : "Mother's document",
    father_document_type                : "Mother's document type",
    eps                                 : "EPS",
    regime                              : "Regime",
    socioeconomic_level                 : "Socioeconomic level", 
    moderator_fee                       : "Moderator fee",
    moderator_fee_value                 : "Moderator fee value",
    amount                              : "Amount",
    information_patient                 : "Information of the patiente",
    family_data                         : "Family data",
    insurance_information               : "Insurance information",
    job                                 : "Job",
    confirm_password                    : "Confirm password",
    service_provider                    : "Service provider",
    name_service                        : "Name Service",
    days_response                       : "Days Response",
    supplier                            : "Supplier",
    laboratory                          : "Laboratory",
    radiology                           : "Radiology",        
    supply                              : "Supply",
    laboratories                        : "Laboratories",
    radiology                           : "Radiology",
    supplies                            : "Supplies",
    laboratory_centers                  : "Laboratory centers",
    radiology_centers                   : "Radiology centers",
    pharmacy_centers                    : "Pharmacy centers",
    supply_centers                      : "Supply centers",
    requires_authorization              : "Requires authorization",
    EPS                                 : "EPS",
    file_selection                      : "File selection",
    file                                : "File",
    new_procedure                       : "New procedure",
    information                         : "Information",
    new_service                         : "New service",
    settings                            : "Settings", 
    procedure                           : "Procedure",
    answers                             : "Answers",
    invoice                             : "Invoice", 
    shopping_cart                       : "Shopping cart",
    info_patient                        : "Information patient",
    contract                            : "Contract",
    attention_number                    : "Attention number",
    user_loged                          : "User loged",
    relationship                        : "Relationship",
    new_familiar                        : "New familiar",
    type_document                       : "Type document",
    typeId                              : "Type document",        
    numberId                            : "Document",
    allergic                            : "Allergic",
    glasgow                             : "Glasgow",
    glucometry                          : "Glucometry",
    temperature                         : "Temperature",
    size                                : "Size",
    weight                              : "Weight",
    pregnancy                           : "Pregnancy",
    fr                                  : "Fr", 
    fc                                  : "Fc", 
    pa1                                 : "Pa1", 
    pa                                  : "Pa", 
    isc                                 : "Isc", 
    f                                   : "F", 
    u                                   : "U", 
    r                                   : "R", 
    tg                                  : "T.G", 
    f1                                  : "F1", 
    p                                   : "P", 
    p1                                  : "P1", 
    g                                   : "G", 
    p2                                  : "P2", 
    a                                   : "A",
    c                                   : "C",
    allergic                            : "Allergic",
    glasgow                             : "Glasgow",
    glucometry                          : "Glucometry",        
    size                                : "Size",
    weight                              : "Weight",
    pregnancy                           : "Pregnancy",
    pregnancyTime                       : "PregnancyTime",
    cause                               : "Cause",
    cytology                            : "Cytology",
    result                              : "Result",
    transferred                         : "Transferred",
    hour                                : "Hour",
    medicalSignature                    : "MedicalSignature",
    companion                           : "Companion",
    pregnancyTime                       : "PregnancyTime",
    cause                               : "Cause",
    cytology                            : "Cytology",
    result                              : "Result",
    transferred                         : "Transferred",
    hour                                : "Hour", 
    medicalSignature                    : "MedicalSignature", 
    companion                           : "Companion", 
    clinicHistory                       : "ClinicHistory", 
    registeredNumber                    : "RegisteredNumber", 
    diagnosis                           : "Diagnosis", 
    observation                         : "Observation", 
    emergencyMedicalHistory             : "EmergencyMedicalHistory", 
    illness                             : "Illness", 
    familyBackground                    : "FamilyBackground", 
    observation                         : "Observation", 
    paraclinical                        : "Paraclinical", 
    diagnosticImpression                : "DiagnosticImpression", 
    plan                                : "Plan", 
    personalHistory                     : "PersonalHistory", 
    exams                               : "Exams", 
    authorizationNumber                 : "AuthorizationNumber", 
    inability                           : "Inability", 
    typeProcedure                       : "TypeProcedure", 
    source                              : "Source", 
    reason                              : "Reason", 
    startDate                           : "StartDate", 
    endDate                             : "EndDate",
    disabilityDays                      : "DisabilityDays",
    ipAddress                           : "IpAddress",
    position                            : "Position",
    providerIps                         : "ProviderIps",
    observation                         : "Observation",
    medical                             : "Medical",
    entity                              : "Entity",
    code                                : "Code",
    cellPhone                           : "CellPhone",
    phone                               : "Phone",
    diagnosticAids                      : "DiagnosticAids",
    orders                              : "Orders",
    medicalFormulas                     : "MedicalFormulas",
    treatment                           : "Treatment",
    medicine                            : "Medicine",
    orderLabs                           : "OrderLabs",
    outpatientOrders                    : "OutpatientOrders",
    specialty                           : "Specialty",
    lift                                : "Lift",
    internalMedicine                    : "InternalMedicine",
    dentalMedicalHistory                : "DentalMedicalHistory",
    socialSecurity                      : "SocialSecurity", 
    dateAdmission                       : "DateAdmission", 
    dentalHistory                       : "DentalHistory", 
    medicalTreatment                    : "MedicalTreatment",         
    processName                         : "ProcessName", 
    odontogramImage                     : "OdontogramImage", 
    image                               : "Image", 
    dentalLetter                        : "DentalLetter", 
    toothNumber                         : "ToothNumber", 
    tooth                               : "Tooth", 
    dentalSide                          : "DentalSide", 
    egressDate                          : "EgressDate", 
    epicrisis                           : "Epicrisis", 
    days                                : "Days", 
    justification                       : "Justification", 
    plan                                : "Plan", 
    epicrisisMedicines                  : "EpicrisisMedicines", 
    medicine                            : "Medicine", 
    dose                                : "Dose", 
    since                               : "Since", 
    until                               : "Until", 
    hospitalExpenses                    : "HospitalExpenses", 
    membership                          : "Membership",
    hospitalization                     : "Hospitalization",
    accountCut                          : "AccountCut",
    diagnosedImages                     : "DiagnosedImages",
    supplies                            : "Supplies",
    laboratories                        : "Laboratories",
    otherServices                       : "OtherServices",
    observations                        : "Observations",
    IdxIncome                           : "IdxIncome",
    IdxEgress                           : "IdxEgress",
    RelatedIdx                          : "RelatedIdx",
    subDiagnoses                        : "SubDiagnoses",
    diagnosticId                        : "DiagnosticId",
    subTreatments                       : "SubTreatments",
    treatmentId                         : "TreatmentId",
    supplies                            : "Supplies",
    who                                 : "Who",
    timeSupply                          : "TimeSupply",
    supplyDate                          : "SupplyDate",
    medicineSupplied                    : "MedicineSupplied",
    whoApplies                          : "WhoApplies",
    membership                          : "Membership",
    serviceAuthorization                : "ServiceAuthorization", 
    serviceNumber                       : "ServiceNumber", 
    expeditionDate                      : "ExpeditionDate", 
    code                                : "Code", 
    sisbenNumber                        : "SisbenNumber", 
    license                             : "License", 
    file                                : "File", 
    modality                            : "Modality", 
    departureDate                       : "DepartureDate", 
    level                               : "Level", 
    service                             : "Service", 
    specialty                           : "Specialty", 
    ambit                               : "Ambit", 
    valid                               : "Valid", 
    originRequest                       : "OriginRequest",
    observation                         : "Observation",
    number                              : "Number",
    medicalDate                         : "MedicalDate",
    person                              : "Person",
    inventories                         : "Inventories",
    expirationDate                      : "ExpirationDate",
    vat                                 : "Vat",
    amount                              : "Amount",
    stock                               : "Stock",
    unitQuantity                        : "UnitQuantity",
    dc                                  : "Dc",
    unitValue                           : "UnitValue",
    totalValuePerProduct                : "TotalValuePerProduct",
    discount                            : "Discount",
    medicineDispatch                    : "MedicineDispatch",
    establishment                       : "Establishment",
    paymentCondition                    : "PaymentCondition",
    seller                              : "Seller",
    city                                : "City",
    purchaseOrder                       : "PurchaseOrder",
    invoiceDate                         : "InvoiceDate",
    expirationDate                      : "ExpirationDate",
    referralNumber                      : "ReferralNumber",
    total                               : "Total",
    billAdditional                      : "BillAdditional",
    procedureType                       : "ProcedureType",
    billPharmacy                        : "BillPharmacy",
    presentation                        : "Presentation",
    concentration                       : "Concentration",
    worth                               : "Worth",
    invoiceLab                          : "InvoiceLab",
    service                             : "Service",
    invoice                             : "Invoice",
    departureDate                       : "DepartureDate",
    invoiceNumber                       : "InvoiceNumber",
    medicationInvoice                   : "MedicationInvoice",
    code                                : "Code",
    description                         : "Description",
    diagnosticList                      : "DiagnosticList",
    medicationList                      : "MedicationList",
    treatmentList                       : "TreatmentList",
    tariffManual                        : "TariffManual",
    medicines                           : "Medicines",
    medicinePrices2                     : "MedicinePrices2",
    configurableMedications             : "ConfigurableMedications",
    medicinePrices                      : "MedicinePrices",
    doctors                             : "Doctors",
    evolutionNotes                      : "EvolutionNotes",
    notifications                       : "Notifications",
    cppypsForm                          : "CppypsForm",
    procedures                          : "Procedures",
    rooted                              : "Rooted",
    turns                               : "Turns",
    auditor                             : "Auditor",
    atcCode                             : "AtcCode",
    activePrinciple                     : "ActivePrinciple",
    pharmaceuticalForm                  : "PharmaceuticalForm",
    clarification                       : "Clarification",
    examId                              : "ExamId",
    points                              : "Points",
    pesos                               : "Pesos",
    medicationId                        : "MedicationId",
    marketId                            : "MarketId",
    maximumPrice                        : "MaximumPrice",
    headline                            : "Headline",
    atcInvites                          : "AtcInvites",
    unit                                : "Unit",
    purchaseValue                       : "PurchaseValue",
    purchaseValue2                      : "PurchaseValue2",
    units                               : "Units",
    saleByEps                           : "SaleByEps",
    hourValue                           : "HourValue",
    halfHourValue                       : "HalfHourValue",
    receiver                            : "Receiver",
    sender                              : "Sender",
    affair                              : "Affair",
    message                             : "Message",
    entryNumber                         : "EntryNumber",
    specialtyCode                       : "SpecialtyCode",
    remissionDate                       : "RemissionDate",
    referralTime                        : "ReferralTime",
    codeEnabledESE                      : "CodeEnabledESE",
    reasonRefers                        : "ReasonRefers",
    serviceCode                         : "ServiceCode",
    agendaId                            : "AgendaId",
    startTime                           : "StartTime",
    endTime                             : "EndTime",
    campus                              : "Campus",
    audit                               : "Audit",
    form                                : "Form",
    mobilityCode                        : "Mobility code",
    save                                : "Save", 
    cellphone                           : "Cellphone",
    Parentesco                          : "Relationship",
    generate_attention                  : "Generate attention",
    error_generate_attention            : "Error Generating attention, review information",
    error_generate_service              : "Error Generating Service, check information",
    assignedDate                        : "Assigned Date", 
    medical_module                      : "Medical Module",
    nursing_module                      : "Nursing Module",
    billing_module                      : "Billing Module",
    pharmacy_module                     : "Pharmacy Module",
    triage_classification               : "Triage classification",
    process_status                      : "Process status",
    recentCytology                      : "Recent cytology",
    update                              : "Update",
    patient_info_required               : "Patient information is required",
    service_generated                   : "Service Generated",
    require_id_update                   : "Require ID to update",
    saving_information                  : "Saving information",
    registered_information              : "Registered Information",
    info_found                          : "Information Found",
    confirm_delete                      : "Confirm delete",
    confirm                             : "Confirm",
    close                               : "Close",
    element_deletion_error              : "Element deletion error",
    deleted_item                        : "Deleted item",
    deleting_element                    : "Deleting element",
    current_disease_previous_personal   : "Current disease / Previous personal",
    personal_background                 : "Personal Background",
    vital_parameters                    : "Vital Parameters",
    pathological_history                : "Pathological History",
    patient_reception                   : "Patient reception",
    antecedent                          : "Antecedent",
    physical_exam                       : "Physical exam",
    normal_altered                      : "Normal / Altered",
    examined                            : "Examined",
    typeRelationship                    : "TypeRelationship",
    MaritalStatus                       : "Marital Status",
    typeAttention                       : "Type Attention",
    motive                              : "Motive",
    background                          : "Background", 
    found_patient_information           : "Found Patient Information",
    no_patient_information_found        : "No patient information found",
    edit_family                         : "Edit Family",
    error_deleting_information          : "Error deleting information",
    recent_services                     : "Recent services",
    continue_service                    : "Continue service",
    searching_patient                   : "Searching patient",
    patient_status_changed              : "Patient status changed",
    continue_service_msg                : "Continue if medical appointment, pending, or last departure time was 24 hours ago",              
    care_information                    : "Care information",
    date_service                        : "Date of service",
    medico_on_duty                      : "Medico on duty",
    add                                 : "Add",
    update_status                       : "Update status",
    invoice_information                 : "Invoice information",
    add_medicine                        : "Add medicine",
    tariff_manual                       : "Tariff manual",
    updating_element                    : "Updating element", 
    item_updated                        : "Item Updated",
    error_updating_element              : "Error Updating Element",
    error                               : "Error",
    dashboard_nursing                   : "Nursing",
    program                             : "Program",
    programs                            : "programs",
    idxDate                             : "IDX Date",
    whoSuppliedIt                       : "Who supplied it",
    supplyTime                          : "Supply time",
    supplyDate                          : "Supply Date",
    whoAppliesIt                        : "Who applies it",
    input                               : "Input",
    invoiced                            : "Invoiced",
    updated_invoice                     : "Updated invoice",
    triage                              : "Triage",
    diagnostic_imaging                  : "Diagnostic Imaging",
    diagnostics                         : "Diagnostics",
    qx                                  : "QX",
    comment                             : "Comment",
    module_admission_description        : "Module of admissions of patients",
    module_nursing_description          : "Module of nursing for attention patients",
    module_medico_description           : "Module of medico and attention patients",
    module_pharmacy_description         : "Module of pharmacy for inventory and dispatch medicine",
    module_management_description       : "Module of management for admistration",
    module_billing_description          : "Module of billing for generate invoices",
    module_audits_description           : "Module of audits for check process and forms",
    module_centers_description          : "Module of centers for management of different centers",
    module_systems_description          : "Module of systems for management system and request issues",
    centers                             : "Centers",
    redirect                            : "Redirect",
    loading                             : "Loading",
    no_information_found                : "No information found",
    no_triage_information_found         : "No triage information found",
    medical_records                     : "Medical records",
    dental_stories                      : "Dental stories",
    medical_notes                       : "Medical notes",
    nursing_notes                       : "Nursing notes",
    laboratory_orders                   : "Laboratory orders",
    medical_orders                      : "Medical orders",      
    medical_formulas                    : "Medical formulas",
    diagnoses                           : "Diagnoses",
    hospital_expenses                   : "Hospital expenses",
    inability                           : "Inability",
    epicrisis                           : "Epicrisis",
    audit_notes                         : "Audit notes",
    nursing_supply_sheet                : "Nursing supply sheet",
    timeElapsed                         : "Time elapsed",
    new_admin                           : "New admin",
    update_admin                        : "Update admin",
    center_type                         : "Center type",
    add_staff                           : "Add staff",
    add_user                            : "Add user",
    edit_user                           : "Edit user",
    add_convention                      : "Add convention",
    edit_agreement                      : "Edit agreement",
    final_date                          : "Final date",
    module                              : "Module",
    lcte                                : "LCTE",
    value_per_product                   : "Value per Product",
    total_quantity_per_product          : "Total quantity per Product",
    stock                               : "Stock",
    medication_request                  : "Medication request",
    add_position                        : "Add position",
    update_position                     : "Update position",
    you_dont_have_messages              : "You dont have messages",
    profile                             : "Profile",
    professional_card                   : "Professional card",
    change_password                     : "Change password",
    saved                               : "Saved",
    updated                             : "Updated",
    re_enter                            : "Re-enter",
    cups                                : "Cups",
    cup                                 : "Cup",
    dosage                              : "Dosage",
    code_cups                           : "Code cups",
    code_cup                            : "Code cup",
    error_loading_service_reload_page   : "error loading service, reload page",
    admission_module                    : "Admission module",
    authorization_service               : "Authorization Service",
    reason_for_consultation             : "Reason for consultation",
    FUR                                 : "F.U.R",
    FPP                                 : "F.P.P",
    HO                                  : "H.O",
    obstetric_history                   : "Obstetric History",
    recent_cytology                     : "Recent cytology",
    userPosition                        : "Name and Position of the person who performs the triage",
    transfer_to_another_center          : "Recommendation of transfer to another Center",
    go_back                             : "Go Back",
    category                            : "Category",
    add_new_administrator               : "Add new Administrator",
    add_administrator                   : "Add Administrator",
    user                                : "User",
    validUntil                          : "Valid until",
    numberAgremment                     : "Agreement number",        
    discountRate                        : "Discount rate",
    percentage                          : "Percentage",
    Fecha                               : "Fecha",

}