export default {
    infoReconvery                       : "Informacion de recuperacion",
    status                              : "Estado",
    DiagnoseSurgery                     : "Diagnósticos de Cirugia",
    Materials                           : "Materiales",    
    MedicalEvolution                    : "Notas de Evolucion",   
    "emergency-medical-history"         : "Historia clinica de urgencia",
    "Ordenes Medicas"                   : "Ordenes Medicas", 
    day                                 : "Dia",
    month                               : "Mes",
    anestheticTechnique                 : "Técnica anestésica", 
    InfoAnestheticRecords               : "Informacion de registro anestesico",  
    AnestheticRecordsSurgery            : "Registros Anestesicos",
    msg_chest                           : "SIMÉTRICO EXPANSIBLE, NOTIRAJES PULMONES CLAROS,  BIEN VENTILADOS CON MURMULLO VESICULAR PRESENTE, RUIDOS CARDÍACOS RÍTMICOS SIN SOPLOS NO AGREGADOS.",
    msg_abdomen                         : "BLANDO, DEPRESIBLE, NO DOLOROSO, NO MASAS, NO MEGALIAS, PERISISTALCIS PRESENTE, NO SIGNOS DE IRRITACIÓN PERITONEAL",
    msg_extremities                     : "EUTROFICAS MOVILES, NO EDEMAS, NO SIGNOS TVP DIGITOPRESION MENOR A DOS SEGUNDOS, REFLEJOS PRESENTES",
    msg_neurological                    : "CONSCIENTE, ALERTA ORIENTADO SIN DEFICIT MOTOR NI SENSITIVO, GLOSGOW 15/15",
    msg_genitourinary                   : "DIURESIS PRESENTE NORMOCONFIGURADO PARA EDAD Y SEXO",
    msg_skinFannels                     : "SIN ALTERACIONES",
    msg_lumbarOsteotendinous            : "CONTEXTURA NORMAL SIN CAMBIOS DE LA PIGMENTACIÓN, HIDRATACIÓN, TEXTURA NORMAL",
    msg_headAndNeck                     : "NORMOCEFALO, PUPILAS ISOCORICAS NORMOREACTIVAS A LA LUZ, MUCOSA ORAL HÚMEDA, CUELLO MÓVIL SIN ADENOPATÍAS PALPABLES, OROFARINGE NORMAL, OTOSCOPIO BILATERAL NORMAL",
    orders_discharge                    : "Ordenes de egreso",
    graduation_evolution                : "Evolución de egreso",
    ""                                  : "",
    vital_signs                         : "Signos Vitales",
    SkinFannels                         : "Piel/faneras",
    LumbarOsteotendinous                : "Lumbal/Osteotendinoso",
    InfoSurgeryDescrption               : "Informacion Descripcion de Cirugia",
    formAccessRoutes                    : "Formulario Acceso de Vias",
    operating_room                      : "Sala de cirugia",
    place                               : "Lugar",
    standardized_patient_referral       : "FORMATO ESTANDARIZADO DE REFERENCIA DE PACIENTES",    
    professionalRegistrationNumber      : "Numero de Registro del Profesional",    
    professionalSignature               : "Firma Profesional que remite",    
    relevantClinicalInformation         : "Diligenciar informacion",    
    relevant_clinical_information       : "INFORMACIÓN CLÍNICA RELEVANTE",
    ServiceReferenceRequested           : "Servicio para el cual se solicita la referencia",    
    ServiceRequesting                   : "Servicio que solicita la referencia",
    ext_phone                           : "Numero de extension de Telefono",    
    code_phone                          : "Codigo de Telefono",
    professional_who_requests_service   : "PROFESIONAL QUE SOLICITA LA REFERENCIA Y SERVICIO AL CUAL REMITE",    
    info_responsible_patient            : "DATOS DE LA PERSONA RESPONSABLE DEL PACIENTE",    
    tutorFullName                       : "Nombre del responsable",    
    patientServiceProviderCode          : "Codigo de entidad",    
    patientServiceProviderName          : "Entidad responsable del pago",    
    providerCode                        : "Codigo",
    providerAddress                     : "Direccion",
    providerPhoneCode                   : "Codigo Telefono",
    providerPhoneNumber                 : "Numero de Telefono",
    providerState                       : "Departamento",
    providerCity                        : "Municipio",
    providerNumberId                    : "Numero identificacion",    
    providerTypeId                      : "Tipo de identificacion Prestador",    
    providerName                        : "Nombre Prestador",    
    info_provider                       : "INFORMACIÓN DEL PRESTADOR",
    DashboardSurgery                    : "Cirugia",
    exitStatus                          : "Estado de salida",
    departureReason                     : "Motivo de salida",
    externalCause                       : "Causa externa",
    consultationSPurpose                : "Finalizacion de consulta",//Objetivo de consulta
    diagnosis3Discharge                 : "Diagnóstico 3 Alta",
    diagnosis2Discharge                 : "Diagnóstico 2 Alta",
    diagnosis1Discharge                 : "Diagnóstico 1 Alta",
    mainDischargeDiagnosis              : "Diagnóstico principal de alta",
    orders                              : "Ordenes",
    hospitalizationJustification        : "Justificación de hospitalización",
    evolutions                          : "Evoluciones",
    genitourinary                       : "Genitourinario/Ano",
    neurological                        : "Neurológico",
    extremities                         : "Extremidades",
    abdomen                             : "Abdomen",
    chest                               : "Tórax", 
    headAndNeck                         : "Cabeza y cuello", 
    generalConditionsUponDeparture      : "Condiciones generales a la salida", 
    motorResponse                       : "Respuesta motora", 
    verbalResponse                      : "Respuesta verbal", 
    eyeOpening                          : "Apertura de ojos", 
    pulse                               : "Pulso", 
    respiratoryFr                       : "Fr respiratorio", 
    cardiacFr                           : "Fr cardíaco", 
    arterialTsn                         : "Tsn arterial", 
    available                           : "Disponible", 
    bed                                 : "Cama", 
    ambit                               : "Ambito",
    SelectBed                           : "Seleccionar Cama",     
    SettingsBedsHospitalization         : "Organizar Camas", 
    DiagnosticHelpSurgery               : "Ayudas Diagnosticas",
    OutpatientOrdersSurgery             : "Interconsulta",
    MedicalFormulasSurgery              : "Formulas Medicas",
    LaboratoryOrderSurgery              : "Laboratorio", 
    OsteosynthesisMaterialsSurgery      : "Materiales Osteosistesis",
    RecoverySurgery                     : "Recuperacion", 
    SurgeryProgramming                  : "Programacion de Cirugia",
    InabilitySurgery                    : "Incapacidad",
    RecommendationsSurgery              : "Recomendaciones",
    MedicalNotesSurgery                 : "Evolucion",
    EmergencyMedicalHistorySurgery      : "Historia Clinica",
    initialExecutionDate                : "Fecha inicio Cirugia",
    executionEndDate                    : "Fecha final Cirugia",
    surgeon                             : "Cirujano",
    anesthesiologist                    : "Anestesiólogo",
    instrumenter                        : "Instrumentista",
    assistant                           : "Asistente",
    anesthesiaType                      : "Tipo de anestesia",
    SurgeryDescription                  : "Descripcion de Cirugia", 
    hora                                : "Hora",
    date_entry                          : "Fecha de ingreso",
    fullName                            : "Nombre Completo",
    ExpenseSheetInvoice                 : "Hoja de Gastos",
    diagnostics                         : "Diagnósticos",
    Remission                           : "Remision", 
    review_by_system                    : "Revision por sistema",
    analysis                            : "Analisis",
    xml                                 : "XML",
    administrator                       : "Administrador",
    percent                             : "Porcentaje",
    finalDate                           : "Fecha Final",
    tariffManualType                    : "Tipo de Manual tarifario",  
    numberAgreement                     : "Numero de convenio", 
    authorizationDate                   : "Fecha de Autorizacion",
    from                                : "Desde",
    to                                  : "A",
    until                               : "Hasta",
    prefix                              : "Prefijo",
    initialInvoiceNumber                : "N. Inicio Factura",
    add2                                : "Agregar",
    filing_information                  : "Informacion de Radicado",
    filing                              : "Radicado",
    filingDate                          : "Fecha Radicado",
    filingHour                          : "Hora Radicado",
    type_concept                        : "Tipo de concepto",
    invoice_issue_date                  : "Fecha expedicion factura",
    invoice_due_date                    : "Fecha Vencimiento factura",
    service_and_billing_information     : "Informacion de servicio y factura",
    year                                : "Año", 
    Invoice                             : "Facturacion", 
    Adult                               : "Adulto",
    DocumentRelationship                : "DOCUMENTO DEL FAMILIAR O ACOMPAÑANTE",
    RegistrationNumber                  : "Numero de registro",
    PatientReadmitted                   : "Paciente ReIngresado?",
    imc                                 : "IMC",
    confirm_action                      : "Confirmar Accion", 
    ExpenseSheetNursing                 : "Hoja de Gastos",
    who_performs_triage                 : "Quien realiza triage",
    oxygen_saturation                   : "Saturación de oxigeno",
    heart_rate                          : "Frecuencia cardíaca(FC)",
    respiratory_rate                    : "Frecuencia respiratoria(FR)",
    blood_pressure                      : "Presión arterial(PA)",
    RequestSupplies                     : "Solicitud de Suministros",
    Billing                             : "Facturacion",
    Surgery                             : "Cirugia",
    Hospitalization                     : "Hospitalizacion",
    DiagnosticAid                       : "Ayuda Diagnostica",
    Laboratory                          : "Laboratorio",
    Pharmacy                            : "Farmacia",
    Medico                              : "Medico",
    Audits                              : "Auditoria", 
    Nursing                             : "Enfermeria",
    Management                          : "Gerencia",
    Admissions                          : "Admisiones",
    PROCEDIMIENTO                       : "PROCEDIMIENTO",
    userOrPassIncorrect                 : "Usuario o Contraseña incorrecto",    
    ID                                  : "ID",
    TypeCenterId                        : "Tipo de Centro",
    center                              : "Centro",
    MUNICIPIO                           : "Municipio",
    OrderSurgery                        : "Orden de Cirugia", 
    TypeCenter                          : "Tipo de Centro",
    DashboardDiagnosticAid              : "Ayudas Diagnosticas", 
    diagnostic_aid                      : "Ayudas Diagnosticas", 
    dashboard                           : "",
    LABORATORIO                         : "LABORATORIO",
    FECHA                               : "Fecha",
    PROCEDIMIENTOS                      : "PROCEDIMIENTOS",
    CUPS                                : "CUPS",
    Procedimientos                      : "Procedimientos",
    NonSurgicalProcedures               : "Procedimientos No Quirurgicos",
    SUMINISTRO                          : "Suministro",
    note                                : "Nota",
    orderNumber                         : "Numero de Orden",
    typeOrder                           : "Tipo de Orden",
    DeliveredTo                         : "Entregado a", 
    typeService                         : "Servicio",
    Dispatch                            : "Despacho",
    "FECHA DE EXPIRACION"               : "FECHA DE EXPIRACION",
    "FECHA LTE"                         : "FECHA LTE",
    LTE                                 : "LTE",
    CANTIDAD                            : "CANTIDAD",
    product                             : "Producto",
    RequestForSupplies                  : "Solicitud de Suministros",
    NursingNotes                        : "Notas de Enfermeria",
    ApplicationSupplies                 : "Aplicacion de Suministros",
    "Relidiquidacion de Cuentas"        : "Relidiquidacion de Cuentas",
    "Relidiquidacion de Cuentas. Salida General" : "Relidiquidacion de Cuentas. Salida General",
    Observaciones                       : "Observaciones",
    "IDx Ingreso"                       : "IDx Ingreso",
    "IDx Egreso"                        : "IDx Egreso",
    "IDx Rel"                           : "IDx Rel",
    Qx                                  : "Qx",
    Guardar                             : "Guardar",
    Hora                                : "Hora",
    productValue                        : "Valor de Producto",
    atc                                 : "ATC",
    cum                                 : "CUM",
    invima                              : "Invima",
    Nivel                               : "Nivel",
    paciente                            : "Paciente",
    "Informacion paciente"              : "Informacion Paciente",
    Personales                          : "Personales",
    Familiares                          : "Familiares",

    hello                               : "Hola",
    admissions                          : "Admisiones",
    nursing                             : "Enfermería",
    medico                              : "Medico",
    pharmacy                            : "Farmacia",
    promotion_and_prevention            : "Promoción y prevención",
    specialized_services                : "Servicios especializados",
    eps                                 : "EPS",
    providers                           : "Proveedores",
    laboratories                        : "Laboratorios",
    diagnostic_aids                     : "Ayudas diagnósticas",
    outpatient_consultations            : "Interconsultas ambulatorias",
    non_pos_medications                 : "Medicamentos no pos",
    management                          : "Gerencia",
    administration                      : "Administración",
    billing                             : "Facturación",
    manager                             : "Gestor",
    audits                              : "Auditorias",
    systems                             : "Sistemas",   
    urgency                             : "Urgencia",
    dashboard_medico                    : "Medico",
    n_a                                 : "N. Atention",
    date                                : "Fecha",
    campus                              : "Sede",        
    state                               : "Estado",
    document                            : "Documento",
    patient                             : "Paciente",
    actions                             : "Acciones",                
    cedula                              : "Cedula",
    tarjet_id                           : "Tarjeta de Identificacion",
    passport                            : "Pasaporte",
    search                              : "Buscar",
    contact_name_keysi                  : "Keysi González Fernández",
    contact_tel                         : "Tel  :  315 465 2115 / 3665271", // 301 646 4330 / 301 460 2702
    contact_email                       : "Keysi2510@hotmail.com",
    contact_email1                      : "Ley-antitramite@hotmail.com",
    contact_address                     : "Oficina Kra 12 Calle 114 # 15-08" ,
    conctact_city                       : "Barranquilla - Atlantico",
    anti_procedure_law                  : "ILC-ASC ley anti tramite salud de los colombianos",
    mission                             : "Mision",
    organization_that_guarantees        : "Somos una organizacion que garantiza mejorar las condiciones del servicio de salud convencional, comprometidos con la ética, el respeto al medio ambiente y la eficiencia en la prestación de servicios asistenciales de acuerdo con las normas expedidas por la OMS, Organizacion Mundial de Salud, desarrollando todas las acciones relacionadas con las guías de obligatorio cumplimiento.",
    vision                              : "Vision",
    universal_platform                  : "En el 2028 la App 'L-ASC', sera la plataforma universal para todas las entidades prestadoras de servicios de salud a nivel nacional, con la finalidad de finiquitar los carentes procesos asistenciales, basados en la norma ley-antitramite.", // 2022
    law_enforcement                     : "L-ASC Con Aplicacion de Ley 019 de 2012", // ILC-ASC
    less_paper                          : "Menos Papel",
    system_modeled_for                  : "Sistema Modelado para  requerir menos  papeles  y atender  de  manera  oportuna a los  pacientes",
    fewer_rows                          : "Menos Filas",
    agile_and_efficient_platform        : "Plataforma  agil y eficaz con  atencion rapida dejando atras  las  largas  filas de los  pacientes",
    specialist_on_time                  : "Especialista a tiempo",
    attention_of_doctors                : "La atención de medicos  especializados en menos  tiempo, garantiza  un diagnostico a  tiempo  para su debido  Tratamiento",
    service                             : "Servicio",
    because_the_user                    : "Porque el usuario merece lo mejor",
    landing                             : "Landing",
    some_screenshots                    : "Algunas Capturas de Pantalla",
    contact                             : "Contacto",
    send                                : "Enviar",
    login                               : "Loguearse",
    logout                              : "Salir",
    start                               : "Inicio",
    description                         : "Descripcion",
    screenshots                         : "Capturas",
    contact                             : "Contacto",
    contacts                            : "Contactos",
    register                            : "Registrar",
    name                                : "Nombre",
    email                               : "Correo",
    message                             : "Mensaje",
    username                            : "Usuario",
    password                            : "Contraseña",
    forget_password                     : "Olvide Contraseña",
    second_name                         : "Segundo nombre",
    second_surname                      : "Segundo apellido",
    department                          : "Departamento",
    neighborhood                        : "Barrio",
    occupation                          : "Ocupación",
    companion                           : "Acompañante",
    accompanying_name                   : "Nombre acompañante",
    sex                                 : "Sexo",
    document_type                       : "Tipo de documento",
    lastname                            : "Apellido",
    gender                              : "Genero",
    phone                               : "Teléfono",
    cell_phone                          : "Celular",
    address                             : "Dirección",
    date_birth                          : "Fecha de nacimiento",
    age                                 : "Edad",
    eps_type                            : "Tipo de EPS",
    zone                                : "Zona",
    city                                : "Ciudad",
    other                               : "Otro",
    father_name                         : "Nombre del Padre",
    father_lastname                     : "Apellido del Padre",
    father_document                     : "Documento del Padre",
    father_document_type                : "Tipo de documento del Padre",
    mother_name                         : "Nombre de la Madre",
    mother_surname                      : "Apellido de la Madre",
    mother_document                     : "Documento de la Madre",
    mother_document_type                : "Tipo de documento de la Madre",
    eps                                 : "EPS",
    regime                              : "Regimen",
    socioeconomic_level                 : "Nivel socioeconomico", 
    moderator_fee                       : "Cuota moderadora",
    moderator_fee_value                 : "Valor cuota moderadora",
    amount                              : "Valor",
    information_patient                 : "Informacion del Paciente",
    family_data                         : "Datos Familiares",
    insurance_information               : "Informacion aseguradora",
    job                                 : "Cargo",
    confirm_password                    : "Confirmar contraseña",
    service_provider                    : "Prestador de Servicio",
    name_service                        : "Nombre Servicio",
    days_response                       : "Días Respuesta",
    supplier                            : "Proveedor",
    laboratory                          : "Laboratorio",
    radiology                           : "Radiología",
    supply                              : "Suministro",
    laboratories                        : "Laboratorios",
    radiology                           : "Radiologías",        
    supplies                            : "Suministros",
    laboratory_centers                  : "Centros de laboratorio",
    radiology_centers                   : "Centros de radiología",
    pharmacy_centers                    : "Centros de farmacia",
    supply_centers                      : "Centros de suministro",
    requires_authorization              : "Requiere autorización",
    EPS                                 : "EPS",
    file_selection                      : "Selección de archivo",
    file                                : "Archivo",
    new_procedure                       : "Nuevo trámite",
    information                         : "Información",
    new_service                         : "Nuevo servicio",
    settings                            : "Configuraciones", 
    procedure                           : "Trámites",
    answers                             : "Respuestas",
    invoice                             : "Factura", 
    shopping_cart                       : "Solitud a proveedor",
    info_patient                        : "Informacion de paciente",
    dispatch                            : "Suministros",
    contract                            : "Contrato",
    attention_number                    : "Número de atención",
    user_loged                          : "Usuario logueado",
    relationship                        : "Parentesco",
    relationShip                        : "Parentesco",
    new_familiar                        : "Nuevo familiar",
    type_document                       : "Tipo de documento",
    typeId                              : "Tipo de documento",
    numberId                            : "Documento",
    allergic                            : "Alérgicos",
    glasgow                             : "Glasgow",
    glucometry                          : "Glucometria",
    temperature                         : "Temperatura",
    size                                : "Talla",
    weight                              : "Peso",
    pregnancy                           : "Embarazo",
    fr                                  : "Fr", 
    fc                                  : "Fc", 
    pa1                                 : "Pa1", 
    pa                                  : "Pa", 
    isc                                 : "Isc", 
    f                                   : "F", 
    u                                   : "U", 
    r                                   : "R", 
    tg                                  : "T.G", 
    f1                                  : "F1", 
    p                                   : "P", 
    p1                                  : "P1", 
    g                                   : "G", 
    p2                                  : "P2", 
    a                                   : "A",
    c                                   : "C",        
    pregnancyTime                       : "Tiempo de embarazo",
    cause                               : "Causa",
    cytology                            : "Citologia",
    result                              : "Resultado",
    transferred                         : "Translado",
    hour                                : "Hora",
    medicalSignature                    : "Firma medico",
    companion                           : "Acompañante",
    clinicHistory                       : "Historia clinica", 
    registeredNumber                    : "Numero radicado", 
    diagnosis                           : "Diagnostico", 
    observation                         : "Observacion", 
    emergencyMedicalHistory             : "Historia clinica de urgencias", 
    illness                             : "Enfermedad", 
    familyBackground                    : "Antecedentes familiares",         
    paraclinical                        : "Paraclinico", 
    diagnosticImpression                : "Impresion diagnostica", 
    plan                                : "Plan", 
    personalHistory                     : "Antecendes personales", 
    exams                               : "Examenes", 
    authorizationNumber                 : "Numero de autorizacion", 
    inability                           : "Incapacidad", 
    typeProcedure                       : "Tipo tramite", 
    source                              : "Origen", 
    reason                              : "Motivo", 
    startDate                           : "Fecha inicio", 
    endDate                             : "Fecha fin",
    disabilityDays                      : "Dias incapacidad",
    ipAddress                           : "Direccion IPS",
    position                            : "Cargo",
    providerIps                         : "Ips prestadora",        
    medical                             : "Medico",
    entity                              : "Entidad",
    code                                : "Codigo",
    cellPhone                           : "Celular",
    phone                               : "Telefono",
    diagnosticAids                      : "Ayudas diagnosticas",
    orders                              : "Ordenes",
    medicalFormulas                     : "Formulas medicas",
    treatment                           : "Tratamiento",
    medicine                            : "Medicamento",
    orderLabs                           : "Orden laboratorios",
    outpatientOrders                    : "Orden Interconsulta",
    specialty                           : "Especialidad",
    lift                                : "Sustentacion",
    internalMedicine                    : "Medicina interna",
    dentalMedicalHistory                : "Historia clinica odontologica",
    socialSecurity                      : "Seguridad social", 
    dateAdmission                       : "Fecha de ingreso", 
    dentalHistory                       : "Antecendes odontologicos", 
    medicalTreatment                    : "Tratamiento medico",         
    processName                         : "Nombre proceso", 
    odontogramImage                     : "Imagen odontogramas", 
    image                               : "Imagen", 
    dentalLetter                        : "Carta dental", 
    toothNumber                         : "Numero de diente", 
    tooth                               : "Diente", 
    dentalSide                          : "Lado dental", 
    egressDate                          : "Fecha de egreso", 
    epicrisis                           : "Epicrisis", 
    days                                : "Dias", 
    justification                       : "Justificacion", 
    plan                                : "Plan", 
    epicrisisMedicines                  : "Epicrisis medicinas", 
    medicine                            : "Medicamento", 
    dose                                : "Dosis", 
    since                               : "Desde", 
    until                               : "Hasta", 
    hospitalExpenses                    : "Gastos hospitalarios", 
    membership                          : "Afiliacion",
    hospitalization                     : "Hospitalizacion",
    accountCut                          : "Corte de cuenta",
    diagnosedImages                     : "Imágenes Diagnosticadas",
    supplies1                           : "Insumos",
    laboratories                        : "Laboratorios",
    otherServices                       : "Otros Servicios",
    observations                        : "Observaciones",
    IdxIncome                           : "Idx Ingreso",
    IdxEgress                           : "Idx Egreso",
    RelatedIdx                          : "Idx Relacionado",
    subDiagnoses                        : "Sub diagnosticos",
    diagnosticId                        : "ID diagnostico",
    subTreatments                       : "Sub tratamientos",
    treatmentId                         : "ID tratamiento",
    supplies                            : "Suministros",
    who                                 : "Quien",
    timeSupply                          : "Hora suministro",
    supplyDate                          : "Fecha suminitro",
    medicineSupplied                    : "Medicamento suministrado",
    whoApplies                          : "Quien aplica",    
    serviceAuthorization                : "Autorizacion de servicios", 
    serviceNumber                       : "Numero de servicio", 
    expeditionDate                      : "Fecha de expedicion",          
    sisbenNumber                        : "Numero de sisben", 
    license                             : "Carnet", 
    file                                : "Ficha", 
    modality                            : "Modalidad", 
    departureDate                       : "Fecha de salida", 
    level                               : "Nivel", 
    service                             : "Servicio", 
    ambit                               : "Ambito", 
    valid                               : "Valido", 
    originRequest                       : "Origen de la solicitud",        
    number                              : "Numero",
    medicalDate                         : "Fecha medico",
    person                              : "Persona",
    inventories                         : "Inventarios",
    expirationDate                      : "Fecha de vencimiento",
    vat                                 : "Iva",
    amount                              : "Cantidad",
    stock                               : "Stock",
    unitQuantity                        : "Cantidad unitaria",
    dc                                  : "Dc",
    unitValue                           : "Valor unitario",
    totalValuePerProduct                : "Valor total por producto",
    discount                            : "Descuento",
    medicineDispatch                    : "Despacho medicamentos",
    establishment                       : "Establecimiento",
    paymentCondition                    : "Condicion de pago",
    seller                              : "Vendedor",
    city                                : "Ciudad",
    purchaseOrder                       : "Orden de compra",
    invoiceDate                         : "Fecha de factura",
    referralNumber                      : "Numero de remision",
    total                               : "Total",
    billAdditional                      : "Facturar adicional",
    procedureType                       : "Tipo procedimiento",
    billPharmacy                        : "Facturar farmacia",
    presentation                        : "Presentacion",
    concentration                       : "Concentracion",
    worth                               : "Valor",
    invoiceLab                          : "Facturar laboratorio",        
    invoice                             : "Factura",
    invoiceNumber                       : "Numero de factura",
    medicationInvoice                   : "Factura medicamentos",
    diagnosticList                      : "Lista diagnosticos",
    medicationList                      : "Lista medicamentos",
    treatmentList                       : "Lista tratamientos",
    tariffManual                        : "Manual tarifarios",
    medicines                           : "Medicamentos",
    medicinePrices2                     : "Medicamentos precios 2",
    configurableMedications             : "Medicamentos configurables",
    medicinePrices                      : "Medicamentos precios",
    doctors                             : "Medicos",
    evolutionNotes                      : "Notas de evolucion",
    notifications                       : "Notificaciones",
    cppypsForm                          : "Planilla cppyps",
    procedures                          : "Procedimientos",
    rooted                              : "Radicados",
    turns                               : "Turnos",
    auditor                             : "Auditor",
    atcCode                             : "Codigo atc",
    activePrinciple                     : "Principio activo",
    pharmaceuticalForm                  : "Forma farmaceutica",
    clarification                       : "Aclaracion",
    examId                              : "Identificacion de examen",
    points                              : "Puntos",
    pesos                               : "Pesos",
    medicationId                        : "Identificacion de medicamento",
    marketId                            : "Identificacion de mercado",
    maximumPrice                        : "Precio maximo",
    headline                            : "Titular",
    atcInvites                          : "Atc invima",
    unit                                : "Unidad",
    purchaseValue                       : "Valor de compra",
    purchaseValue2                      : "Valor de compra 2",
    units                               : "Unidades",
    saleByEps                           : "Venta por eps",
    hourValue                           : "Valor hora",
    halfHourValue                       : "Valor media hora",
    receiver                            : "Recibidor",
    sender                              : "Enviador",
    affair                              : "Asunto",
    message                             : "Mensaje",
    entryNumber                         : "Numero de ingreso",
    specialtyCode                       : "Codigo de especialidad",
    remissionDate                       : "Fecha de remision",
    referralTime                        : "Hora de remision",
    codeEnabledESE                      : "Codigo habilitado ESE",
    reasonRefers                        : "Motivo remite",
    serviceCode                         : "Codigo de servicio",
    agendaId                            : "Identificacion de agenda",
    startTime                           : "Hora inicio",
    endTime                             : "Hora fin",
    campus                              : "Sede",
    audit                               : "Auditoria",
    form                                : "Formulario",
    mobilityCode                        : "código de movilidad",
    save                                : "Guardar", 
    cellphone                           : "Celular",
    Parentesco                          : "Parentesco",
    generate_attention                  : "Generar atención",
    error_generate_attention            : "Error Generando atención, revisar information",
    error_generate_service              : "Error generando servicio, revise informacion",
    assignedDate                        : "Fecha Asignada", 
    medical_module                      : "Modulo Medico",
    nursing_module                      : "Modulo de Enfermeria",
    billing_module                      : "Modulo de Facturacion ",
    pharmacy_module                     : "Modulo de Farmacia ",
    triage_classification               : "Clasificación de Triage",
    process_status                      : "Estado de proceso",
    recentCytology                      : "Recent cytology",
    update                              : "Actualizar",
    patient_info_required               : "Se requiere información de Paciente",
    service_generated                   : "Servicio Generado",
    require_id_update                   : "Require ID para actualizar",
    saving_information                  : "Guardando información",
    registered_information              : "Información Registrada",
    info_found                          : "Información Encontrada",
    confirm_delete                      : "Confirmar Borrado",
    confirm                             : "Confirmar",
    close                               : "Cerrar",
    element_deletion_error              : "Error en eliminación de elemento",
    deleted_item                        : "Elemento eliminado",
    deleting_element                    : "Borrando elemento",
    current_disease_previous_personal   : "Enfermedad Actual / Ants. personales",
    personal_background                 : "Antecendentes Personales",
    vital_parameters                    : "Parametros Vitales",
    pathological_history                : "Antecedentes Patológicos", 
    patient_reception                   : "Recepcion del paciente",
    antecedent                          : "Antecedente",
    physical_exam                       : "Examen Fisico",
    normal_altered                      : "Normal / Alterado",
    examined                            : "Examinado",
    typeRelationship                    : "Parentesco",
    MaritalStatus                       : "Estado civil",
    typeAttention                       : "Tipo de Atención",
    motive                              : "Motivo",
    background                          : "Antecedentes",
    found_patient_information           : "Encontrada Informacion de paciente", 
    no_patient_information_found        : "No se encontró información del paciente",
    edit_family                         : "Editar Familiar",
    not_found_route                     : "not_found_route",
    error_deleting_information          : "Error al eliminar información",
    recent_services                     : "Servicios recientes",
    continue_service                    : "Continuar servicio",
    searching_patient                   : "Buscando paciente",
    patient_status_changed              : "Estado del paciente cambiado",
    continue_service_msg                : "Continuar si cita medica, pendiente, o tiempo de ultima salida fue hace 24 horas",              
    care_information                    : "Información de atención",
    date_service                        : "Fecha de Servicio",
    medico_on_duty                      : "Medico de turno",
    add                                 : "Añadir",
    update_status                       : "Actualizar estatus",
    invoice_information                 : "Información de factura",
    add_medicine                        : "Añadir medicamento",
    tariff_manual                       : "Manual tarifario",
    updating_element                    : "Actualizando elemento", 
    item_updated                        : "Elemento Actualizado",
    error_updating_element              : "Error Actualizando Elemento ",
    error                               : "Error",
    dashboard_nursing                   : "Enfermeria",
    program                             : "Programa",
    programs                            : "programas",
    idxDate                             : "Fecha IDX",
    whoSuppliedIt                       : "Quien lo Suministro",
    supplyTime                          : "Hora suministro",
    supplyDate                          : "Fecha Suministro",
    whoAppliesIt                        : "Quien lo aplica",
    input                               : "Insumo",
    invoiced                            : "Facturado",
    updated_invoice                     : "Factura Actualizada",
    triage                              : "Triage",
    diagnostic_imaging                  : "Imágenes Diagnosticas",
    diagnostics                         : "Diagnósticos",
    qx                                  : "QX",
    comment                             : "Comentario",
    module_admission_description        : "Módulo de admisiones de pacientes",
    module_nursing_description          : "Módulo de enfermería para atención de pacientes",
    module_medico_description           : "Modulo de medico y atencion de pacientes",
    module_pharmacy_description         : "Módulo de farmacia para inventario y despacho de medicamentos",
    module_management_description       : "Módulo de gestión para administración",
    module_billing_description          : "Módulo de facturación para generar facturas",
    module_audits_description           : "Módulo de auditorías para proceso de cheques y formularios",
    module_centers_description          : "Módulo de centros para gestión de diferentes centros",
    module_systems_description          : "Módulo de sistemas para el sistema de gestión y solicitudes de problemas",
    centers                             : "Centros",
    loading                             : "Cargando",
    redirect                            : "Redireccionar",        
    no_information_found                : "No se encontró información",
    no_triage_information_found         : "No se encontró información de triage",
    medical_records                     : "Historias clínicas",
    dental_stories                     : "Historias odontológicas",
    medical_notes                       : "Notas medicas",
    nursing_notes                       : "Notas enfermeria",
    laboratory_orders                   : "Ordenes laboratorio",
    medical_orders                      : "Ordenes medicas",      
    medical_formulas                    : "Formulas medicas",
    diagnoses                           : "Diagnosticos",
    hospital_expenses                   : "Gastos hospitalarios",
    inability                           : "Incapacidad",
    epicrisis                           : "Epicrisis",
    audit_notes                         : "Notas de auditoria",
    nursing_supply_sheet                : "Hoja de suministros de enfermería",
    timeElapsed                         : "Tiempo transcurrido",
    new_admin                           : "Nuevo administrador",
    update_admin                        : "Actualizar administrador",
    center_type                         : "Tipo de centro",
    add_staff                           : "Agregar personal",
    add_user                            : "Agregar Usuario",
    edit_user                           : "Editar Usuario",
    add_convention                      : "Agregar convenio",
    edit_agreement                      : "Editar convenio",
    final_date                          : "Fecha final",
    module                              : "Modulo",
    lcte                                : "LCTE",
    value_per_product                   : "Valor por Producto",
    total_quantity_per_product          : "Total cantidad por producto",
    stock                               : "Cantidad",
    medication_request                  : "Solicitud de medicamentos",
    add_position                        : "Agregar cargo",
    update_position                     : "Actualizar cargo",
    you_dont_have_messages              : "Usted no tiene mensajes",
    profile                             : "Perfil",
    professional_card                   : "Tarjeta profesional",
    change_password                     : "Cambiar Contraseña",
    saved                               : "Guardado",
    updated                             : "Actualizado",
    re_enter                            : "Reingresar",
    cups                                : "Cups",
    cup                                 : "Cup",
    dosage                              : "Dosis",
    code_cups                           : "Codigo cups",
    code_cup                            : "Codigo cup",
    error_loading_service_reload_page   : "Error cargando servicio, recargue pagina",
    admission_module                    : "Módulo de admisionista",
    authorization_service               : "Authorizacion de Servicio",
    reason_for_consultation             : "Motivo consulta",
    FUR                                 : "F.U.R",
    FPP                                 : "F.P.P",
    HO                                  : "H.O",
    obstetric_history                   : "Antecedentes Obstétricos",
    recent_cytology                     : "Citología reciente",
    userPosition                        : "Nombre y Cargo de Quien realiza el triage",
    transfer_to_another_center          : "Recomendación de traslado a otro Centro",
    go_back                             : "Regresar",
    category                            : "Categoría",
    add_new_administrator               : "Agregar nueva administradora",
    add_administrator                   : "Agregar administradora",
    user                                : "Usuario",
    validUntil                          : "Vigencia hasta",
    numberAgremment                     : "Número de convenio",
    discountRate                        : "Porcentaje de descuento",
    percentage                          : "Porcentaje",
    
    min_8_characters                    : "Minimo 8 caracteres",
    anexo_2                             : "Anexo 2",
    anexo_3                             : "Anexo 3",
    anexo_9                             : "Anexo 9",
    download_anexo_2                    : "Descargar anexo 2",
    download_anexo_3                    : "Descargar anexo 3",
    download_anexo_9                    : "Descargar anexo 9",
    AuthorizationService                : "Autorizacion de servicios",
    DashboardNursing                    : "Enfermeria",
    DashboardMedico                     : "Medico",
    history                             : "Historial",
    pdf                                 : "PDF",
    download                            : "Descargar",
    AttentionId                         : "Numero de Atencion",
    EvolutionNotes                      : "Notas de Evolucion",
    Formulas                            : "Formulas",
    Outpatient                          : "Ambulatorias",
    ObstetricHistory                    : "Antedecendes Obstétricos",
    LoadingPleaseWait                   : "Cargando... por favor espere",
    isAdult                             : "Es Adulto",
    CAU                                 : "CAU",           
    documentation                       : "Documentación",
    download_furrip                     : "Descargar FURRIP",
    download_soat                       : "Descargar SOAT",
    download_epicrisis                  : "Descargar Epicrisis",
    soat                                : "Soat",
    furips                              : "Furips",
    LoadingPeaseWait                    : "Cargardo...Por favor espere",
    supports                            : "Soportes",
    institutionalReports                : "Reportes Institucionales",
    edit                                : "Editar",
    select                              : "Seleccionar",
    medicamentsAtc                      : "Medicamentos ATC",
    imagesDiagnostics                   : "Imágenes Diagnosticadas",
    care_satisfaction                   : "Formulario de Satisfaccion",
    download_care_satisfaction          : "Descargar Formulario de Satisfaccion",
    prehospital_care                    : "Prehospitalario",
    download_prehospital_care           : "Descargar prehospitalario", 
    furtran                             : "FURTRAN",
    download_furtran                    : "Descargar FURTRAN",
    analysis                            : "Analisis",
    laboratory_module                   : "Modulo de  Laboratorio",
    DashboardLaboratory                 : "Laboratorio",
    "Justificación Clínica"             : "Justificación Clínica",
    Fecha                               : "Fecha",
    DashboardTypesAnalisis              : "Tipos de Analisis",
    deleted                             : "Borrado", 
    DashboardSettingsAnalisis           : "Formatos de laboratorio",
    EmergencyMedicalHistory             : "Historia Clinica Urgencia",
    Ordenes                             : "Ordenes",
    firstLastname                       : "Primer Apellido", 
    MedicalFormulas                     : "Formulas Medicas",
    formulas                            : "Formulas",
    laboratorio                         : "Laboratorio",
    ambulatorias                        : "Ambulatorias",
    "Ayuda diagnostica"                 : "Ayuda Diagnostica", 
    diagnostico                         : "Diagnostico",
    LaboratoryOrder                     : "Ordenes de Laboratorio",
    nombre                              : "Nombre",
    telefono                            : "Telefono",
    direccion                           : "Direccion",
    OutpatientOrders                    : "Orden Interconsulta",
    Laboratorios                        : "Laboratorios",
    DiagnosticHelp                      : "Ayudas Diagnosticas", 
    MedicalNotes                        : "Notas Medicas",
    aseguradora                         : "Aseguradora",
    nit                                 : "NIT",
    Inability                           : "Incapacidad",
    prescriber_information              : "Informacion del prescriptor",
    Epicrisis                           : "Epicrisis",
    surgery                             : "Cirugia",
    recommendation                      : "Recomendaciones",
    Recommendations                     : "Recomendaciones",
    TriageClassification                : "Clasificación de Triage", 
    EmergencyMedicalHistoryHospitalization  : "Historia Clinica",
    ServicesHospitalization                 : "Servicio",
    MedicalFormulasHospitalization          : "Formulas Medicas",
    LaboratoryOrderHospitalization          : "Ordenes de Laboratorio",
    OutpatientOrdersHospitalization         : "Orden Interconsulta",
    DiagnosticHelpHospitalization           : "Ayudas Diagnosticas",
    MedicalNotesHospitalization             : "Notas Medicas",
    RecommendationsHospitalization          : "Recomendaciones",
    EpicrisisHospitalization                : "Epicrisis",
    DischargeHospitalization                : "Egreso",
    InabilityHospitalization                : "Incapacidad",
    StayFormHospitalization                 : "Formulario de Estancia",
    DashboardHospitalization                : "Hospitalizacion",
    infoCenter                              : "Informaction de Centro",
    delete                                  : "Eliminar", 
}